import { defineCategory } from '../define';

const loan = () => import('./loan/tools');
const inv = () => import('./investment/tools');
const dep = () => import('./deposits/tools');
const plan = () => import('./planning/tools');

const LOAN_RELATED = [
  'home-loan-emi-calculator',
  'personal-loan-emi-calculator',
  'car-loan-emi-calculator',
  'loan-eligibility-calculator',
  'loan-tenure-calculator',
  'loan-prepayment-calculator',
];

export const financeTools = defineCategory('finance', [
  {
    slug: 'emi-calculator',
    name: 'EMI Calculator',
    shortDescription:
      'Calculate monthly loan EMI, total interest and total payment with a year-wise schedule.',
    keywords: [
      'emi',
      'loan',
      'monthly emi',
      'loan calculator',
      'equated monthly instalment',
      'interest',
    ],
    aliases: [
      'loan emi',
      'monthly installment',
      'monthly instalment',
      'loan calculator',
      'emi calc',
    ],
    icon: 'calculator',
    isPopular: true,
    isFeatured: true,
    disclaimer: 'finance',
    shareSubject: 'loan EMI',
    relatedTools: LOAN_RELATED,
    load: () => loan().then((m) => m.EmiCalculator),
  },
  {
    slug: 'home-loan-emi-calculator',
    name: 'Home Loan EMI Calculator',
    shortDescription: 'Work out your housing loan EMI, total interest and processing fee cost.',
    keywords: ['home loan', 'housing loan', 'emi', 'mortgage', 'house', 'property loan'],
    aliases: [
      'house loan',
      'home loan emi',
      'housing loan emi',
      'mortgage calculator',
      'flat loan',
    ],
    icon: 'home',
    isPopular: true,
    disclaimer: 'finance',
    shareSubject: 'home loan EMI',
    relatedTools: [
      'emi-calculator',
      'loan-eligibility-calculator',
      'loan-prepayment-calculator',
      'loan-amortization-calculator',
      'hra-calculator',
      'income-tax-calculator',
    ],
    load: () => loan().then((m) => m.HomeLoanEmiCalculator),
  },
  {
    slug: 'personal-loan-emi-calculator',
    name: 'Personal Loan EMI Calculator',
    shortDescription: 'Calculate personal loan EMI including the upfront processing fee.',
    keywords: ['personal loan', 'emi', 'unsecured loan', 'instant loan'],
    aliases: ['personal loan emi', 'pl emi'],
    icon: 'wallet',
    disclaimer: 'finance',
    shareSubject: 'personal loan EMI',
    relatedTools: [
      'emi-calculator',
      'loan-tenure-calculator',
      'loan-eligibility-calculator',
      'loan-prepayment-calculator',
      'business-loan-calculator',
    ],
    load: () => loan().then((m) => m.PersonalLoanEmiCalculator),
  },
  {
    slug: 'car-loan-emi-calculator',
    name: 'Car Loan EMI Calculator',
    shortDescription: 'Find the EMI on a car loan from the on-road price and down payment.',
    keywords: ['car loan', 'auto loan', 'vehicle loan', 'emi', 'car'],
    aliases: ['car emi', 'vehicle emi', 'auto loan emi', 'bike loan'],
    icon: 'car',
    disclaimer: 'finance',
    shareSubject: 'car loan EMI',
    relatedTools: [
      'emi-calculator',
      'fuel-cost-calculator',
      'loan-prepayment-calculator',
      'personal-loan-emi-calculator',
    ],
    load: () => loan().then((m) => m.CarLoanEmiCalculator),
  },
  {
    slug: 'education-loan-emi-calculator',
    name: 'Education Loan EMI Calculator',
    shortDescription:
      'Estimate education loan EMI after the moratorium, including interest accrued while studying.',
    keywords: ['education loan', 'student loan', 'study loan', 'moratorium', 'emi', '80e'],
    aliases: ['student loan emi', 'study abroad loan'],
    icon: 'graduation',
    disclaimer: 'finance',
    shareSubject: 'education loan EMI',
    relatedTools: [
      'emi-calculator',
      'loan-tenure-calculator',
      'cgpa-calculator',
      'loan-prepayment-calculator',
    ],
    load: () => loan().then((m) => m.EducationLoanEmiCalculator),
  },
  {
    slug: 'loan-eligibility-calculator',
    name: 'Loan Eligibility Calculator',
    shortDescription: 'Estimate how much loan you can get based on income and existing EMIs.',
    keywords: [
      'loan eligibility',
      'how much loan',
      'foir',
      'home loan eligibility',
      'income',
      'emi',
      'loan',
    ],
    aliases: ['max loan', 'loan amount eligible', 'how much home loan can i get'],
    icon: 'target',
    disclaimer: 'finance',
    relatedTools: [
      'home-loan-emi-calculator',
      'emi-calculator',
      'loan-tenure-calculator',
      'ctc-to-in-hand-salary-calculator',
    ],
    load: () => loan().then((m) => m.LoanEligibilityCalculator),
  },
  {
    slug: 'loan-tenure-calculator',
    name: 'Loan Tenure Calculator',
    shortDescription: 'Find how long it takes to repay a loan with the EMI you can afford.',
    keywords: ['loan tenure', 'repayment period', 'how long', 'emi', 'loan duration'],
    aliases: ['loan duration', 'months to repay'],
    icon: 'hourglass',
    disclaimer: 'finance',
    relatedTools: LOAN_RELATED.filter((s) => s !== 'loan-tenure-calculator').concat(
      'emi-calculator',
    ),
    load: () => loan().then((m) => m.LoanTenureCalculator),
  },
  {
    slug: 'loan-prepayment-calculator',
    name: 'Loan Prepayment Calculator',
    shortDescription:
      'See how much interest you save by prepaying your loan and how tenure or EMI changes.',
    keywords: [
      'prepayment',
      'part payment',
      'foreclosure',
      'interest saved',
      'home loan prepayment',
    ],
    aliases: ['part prepayment', 'loan part payment', 'prepay home loan'],
    icon: 'trending',
    disclaimer: 'finance',
    relatedTools: [
      'home-loan-emi-calculator',
      'loan-amortization-calculator',
      'emi-calculator',
      'loan-tenure-calculator',
    ],
    load: () => loan().then((m) => m.LoanPrepaymentCalculator),
  },
  {
    slug: 'loan-amortization-calculator',
    name: 'Loan Amortization Calculator',
    shortDescription:
      'Generate a month-by-month loan amortization schedule with principal, interest and balance.',
    keywords: ['amortization', 'amortisation', 'repayment schedule', 'emi schedule', 'loan table'],
    aliases: ['amortization schedule', 'emi chart', 'loan schedule'],
    icon: 'list',
    disclaimer: 'finance',
    relatedTools: [
      'emi-calculator',
      'loan-prepayment-calculator',
      'home-loan-emi-calculator',
      'loan-tenure-calculator',
    ],
    load: () => loan().then((m) => m.LoanAmortizationCalculator),
  },
  {
    slug: 'sip-calculator',
    name: 'SIP Calculator',
    shortDescription: 'Estimate the future value of your monthly mutual fund SIP.',
    keywords: [
      'sip',
      'mutual fund',
      'systematic investment plan',
      'investment',
      'returns',
      'monthly investment',
    ],
    aliases: ['mutual fund calculator', 'sip returns', 'mf sip'],
    icon: 'trending',
    isPopular: true,
    isFeatured: true,
    disclaimer: 'finance',
    shareSubject: 'SIP returns',
    relatedTools: [
      'sip-returns-calculator',
      'lump-sum-calculator',
      'swp-calculator',
      'stp-calculator',
      'cagr-calculator',
      'retirement-calculator',
    ],
    load: () => inv().then((m) => m.SipCalculator),
  },
  {
    slug: 'sip-returns-calculator',
    name: 'SIP Returns Calculator',
    shortDescription:
      'Project step-up SIP returns and see the value in today’s money after inflation.',
    keywords: [
      'sip returns',
      'step up sip',
      'top up sip',
      'mutual fund',
      'investment',
      'inflation adjusted',
    ],
    aliases: ['step-up sip', 'sip with increase', 'top-up sip'],
    icon: 'lineChart',
    disclaimer: 'finance',
    shareSubject: 'SIP returns',
    relatedTools: [
      'sip-calculator',
      'lump-sum-calculator',
      'inflation-calculator',
      'retirement-calculator',
    ],
    load: () => inv().then((m) => m.SipReturnsCalculator),
  },
  {
    slug: 'lump-sum-calculator',
    name: 'Lump Sum Calculator',
    shortDescription: 'Calculate the future value of a one-time investment.',
    keywords: ['lump sum', 'lumpsum', 'one time investment', 'mutual fund', 'investment'],
    aliases: ['one-time investment', 'lumpsum returns'],
    icon: 'coins',
    disclaimer: 'finance',
    relatedTools: ['sip-calculator', 'cagr-calculator', 'fd-calculator', 'future-value-calculator'],
    load: () => inv().then((m) => m.LumpSumCalculator),
  },
  {
    slug: 'swp-calculator',
    name: 'SWP Calculator',
    shortDescription: 'Plan systematic withdrawals and see how long your corpus lasts.',
    keywords: [
      'swp',
      'systematic withdrawal plan',
      'monthly income',
      'withdrawal',
      'retirement income',
    ],
    aliases: ['withdrawal plan', 'monthly withdrawal'],
    icon: 'banknote',
    disclaimer: 'finance',
    relatedTools: [
      'sip-calculator',
      'stp-calculator',
      'retirement-corpus-calculator',
      'nps-calculator',
    ],
    load: () => inv().then((m) => m.SwpCalculator),
  },
  {
    slug: 'stp-calculator',
    name: 'STP Calculator',
    shortDescription: 'Model a systematic transfer from a liquid or debt fund into an equity fund.',
    keywords: ['stp', 'systematic transfer plan', 'liquid fund', 'equity', 'transfer'],
    aliases: ['transfer plan'],
    icon: 'swap',
    disclaimer: 'finance',
    relatedTools: ['sip-calculator', 'swp-calculator', 'lump-sum-calculator'],
    load: () => inv().then((m) => m.StpCalculator),
  },
  {
    slug: 'fd-calculator',
    name: 'FD Calculator',
    shortDescription:
      'Calculate fixed deposit maturity amount and interest with quarterly compounding.',
    keywords: ['fd', 'fixed deposit', 'bank fd', 'interest', 'maturity', 'senior citizen fd'],
    aliases: ['fixed deposit calculator', 'fd interest', 'term deposit'],
    icon: 'bank',
    isPopular: true,
    disclaimer: 'finance',
    shareSubject: 'FD maturity',
    relatedTools: [
      'rd-calculator',
      'ppf-calculator',
      'compound-interest-calculator',
      'tds-calculator',
    ],
    load: () => dep().then((m) => m.FdCalculator),
  },
  {
    slug: 'rd-calculator',
    name: 'RD Calculator',
    shortDescription: 'Find the maturity value of a recurring deposit.',
    keywords: ['rd', 'recurring deposit', 'post office rd', 'monthly deposit', 'savings'],
    aliases: ['recurring deposit calculator'],
    icon: 'piggy',
    disclaimer: 'finance',
    relatedTools: ['fd-calculator', 'sip-calculator', 'ppf-calculator'],
    load: () => dep().then((m) => m.RdCalculator),
  },
  {
    slug: 'ppf-calculator',
    name: 'PPF Calculator',
    shortDescription: 'Calculate Public Provident Fund maturity with a year-wise balance table.',
    keywords: ['ppf', 'public provident fund', 'tax free', '80c', 'savings', 'post office'],
    aliases: ['provident fund calculator', 'ppf maturity'],
    icon: 'piggy',
    isPopular: true,
    disclaimer: 'finance',
    relatedTools: ['epf-calculator', 'nps-calculator', 'fd-calculator', 'tax-saving-calculator'],
    load: () => dep().then((m) => m.PpfCalculator),
  },
  {
    slug: 'nps-calculator',
    name: 'NPS Calculator',
    shortDescription: 'Estimate your National Pension System corpus, lump sum and monthly pension.',
    keywords: ['nps', 'national pension system', 'pension', 'annuity', 'retirement', '80ccd'],
    aliases: ['pension calculator', 'nps pension'],
    icon: 'piggy',
    disclaimer: 'finance',
    relatedTools: ['retirement-calculator', 'ppf-calculator', 'epf-calculator', 'swp-calculator'],
    load: () => dep().then((m) => m.NpsCalculator),
  },
  {
    slug: 'cagr-calculator',
    name: 'CAGR Calculator',
    shortDescription: 'Calculate the compound annual growth rate between two values.',
    keywords: [
      'cagr',
      'compound annual growth rate',
      'annualised return',
      'growth rate',
      'investment',
    ],
    aliases: ['annual growth', 'annualized return'],
    icon: 'trending',
    disclaimer: 'finance',
    relatedTools: [
      'investment-return-calculator',
      'lump-sum-calculator',
      'rule-of-72-calculator',
      'roi-calculator',
    ],
    load: () => inv().then((m) => m.CagrCalculator),
  },
  {
    slug: 'simple-interest-calculator',
    name: 'Simple Interest Calculator',
    shortDescription: 'Calculate simple interest and total amount for any period.',
    keywords: ['simple interest', 'si', 'interest', 'principal', 'rate'],
    aliases: ['si calculator', 'prt'],
    icon: 'percent',
    alsoIn: ['math'],
    disclaimer: 'finance',
    relatedTools: ['compound-interest-calculator', 'fd-calculator', 'emi-calculator'],
    load: () => dep().then((m) => m.SimpleInterestCalculator),
  },
  {
    slug: 'compound-interest-calculator',
    name: 'Compound Interest Calculator',
    shortDescription:
      'Calculate compound interest with any compounding frequency and monthly additions.',
    keywords: ['compound interest', 'ci', 'compounding', 'interest', 'growth'],
    aliases: ['ci calculator', 'interest on interest'],
    icon: 'percent',
    alsoIn: ['math'],
    disclaimer: 'finance',
    relatedTools: [
      'simple-interest-calculator',
      'fd-calculator',
      'future-value-calculator',
      'sip-calculator',
    ],
    load: () => dep().then((m) => m.CompoundInterestCalculator),
  },
  {
    slug: 'inflation-calculator',
    name: 'Inflation Calculator',
    shortDescription: 'See how inflation raises future costs and erodes purchasing power.',
    keywords: ['inflation', 'purchasing power', 'future cost', 'price rise', 'cpi'],
    aliases: ['future value of money', 'cost of living'],
    icon: 'trending',
    disclaimer: 'finance',
    relatedTools: [
      'retirement-calculator',
      'future-value-calculator',
      'present-value-calculator',
      'sip-returns-calculator',
    ],
    load: () => plan().then((m) => m.InflationCalculator),
  },
  {
    slug: 'retirement-calculator',
    name: 'Retirement Calculator',
    shortDescription: 'Plan the corpus and monthly SIP you need to retire comfortably.',
    keywords: ['retirement', 'retirement planning', 'corpus', 'pension', 'fire', 'sip'],
    aliases: ['retirement planner', 'early retirement', 'fire calculator'],
    icon: 'piggy',
    isFeatured: true,
    disclaimer: 'finance',
    relatedTools: [
      'retirement-corpus-calculator',
      'nps-calculator',
      'sip-calculator',
      'inflation-calculator',
      'epf-calculator',
    ],
    load: () => plan().then((m) => m.RetirementCalculator),
  },
  {
    slug: 'retirement-corpus-calculator',
    name: 'Retirement Corpus Calculator',
    shortDescription: 'Find the corpus needed to fund your expenses through retirement.',
    keywords: ['retirement corpus', 'how much to retire', 'corpus', 'retirement fund'],
    aliases: ['corpus needed', 'retirement fund size'],
    icon: 'piggy',
    disclaimer: 'finance',
    relatedTools: [
      'retirement-calculator',
      'swp-calculator',
      'nps-calculator',
      'inflation-calculator',
    ],
    load: () => plan().then((m) => m.RetirementCorpusCalculator),
  },
  {
    slug: 'net-worth-calculator',
    name: 'Net Worth Calculator',
    shortDescription: 'Add up assets and liabilities to calculate your personal net worth.',
    keywords: ['net worth', 'assets', 'liabilities', 'wealth', 'balance sheet'],
    aliases: ['personal net worth', 'wealth calculator'],
    icon: 'scale',
    disclaimer: 'finance',
    relatedTools: ['retirement-calculator', 'investment-return-calculator', 'emi-calculator'],
    load: () => plan().then((m) => m.NetWorthCalculator),
  },
  {
    slug: 'investment-return-calculator',
    name: 'Investment Return Calculator',
    shortDescription:
      'Calculate absolute and annualised return on any investment, including dividends.',
    keywords: [
      'investment return',
      'return on investment',
      'profit',
      'stock return',
      'absolute return',
      'investment',
    ],
    aliases: ['stock return calculator', 'portfolio return'],
    icon: 'lineChart',
    disclaimer: 'finance',
    relatedTools: [
      'cagr-calculator',
      'roi-calculator',
      'capital-gains-calculator',
      'lump-sum-calculator',
    ],
    load: () => inv().then((m) => m.InvestmentReturnCalculator),
  },
  {
    slug: 'future-value-calculator',
    name: 'Future Value Calculator',
    shortDescription: 'Calculate the future value of money with optional periodic payments.',
    keywords: ['future value', 'fv', 'time value of money', 'annuity', 'compounding'],
    aliases: ['fv calculator'],
    icon: 'trending',
    disclaimer: 'finance',
    relatedTools: [
      'present-value-calculator',
      'compound-interest-calculator',
      'inflation-calculator',
    ],
    load: () => inv().then((m) => m.FutureValueCalculator),
  },
  {
    slug: 'present-value-calculator',
    name: 'Present Value Calculator',
    shortDescription: 'Discount a future amount or stream of payments to today’s value.',
    keywords: ['present value', 'pv', 'discounting', 'npv', 'annuity', 'time value of money'],
    aliases: ['pv calculator', 'discount calculator finance'],
    icon: 'coins',
    disclaimer: 'finance',
    relatedTools: ['future-value-calculator', 'inflation-calculator', 'cagr-calculator'],
    load: () => inv().then((m) => m.PresentValueCalculator),
  },
  {
    slug: 'rule-of-72-calculator',
    name: 'Rule of 72 Calculator',
    shortDescription: 'Estimate how long it takes to double your money at a given return.',
    keywords: ['rule of 72', 'double money', 'doubling time', 'rule of 114', 'rule of 144'],
    aliases: ['money double', 'how long to double'],
    icon: 'timer',
    disclaimer: 'finance',
    relatedTools: ['cagr-calculator', 'compound-interest-calculator', 'lump-sum-calculator'],
    load: () => inv().then((m) => m.RuleOf72Calculator),
  },
]);
