import { defineCategory } from '../define';

const t = () => import('./tools');
const COUNT = [
  'word-counter',
  'character-counter',
  'sentence-counter',
  'paragraph-counter',
  'line-counter',
  'reading-time-calculator',
];
const CASE = [
  'case-converter',
  'uppercase-converter',
  'lowercase-converter',
  'title-case-converter',
];
const others = (list: string[], self: string, extra: string[] = []) =>
  [...list.filter((s) => s !== self), ...extra].slice(0, 6);

export const textTools = defineCategory('text', [
  {
    slug: 'word-counter',
    name: 'Word Counter',
    shortDescription:
      'Count words, characters, sentences and paragraphs with reading time and keyword frequency.',
    keywords: ['word count', 'word counter', 'count words', 'essay', 'characters', 'text'],
    aliases: ['words count', 'wordcount', 'how many words'],
    icon: 'type',
    isPopular: true,
    localOnly: true,
    relatedTools: others(COUNT, 'word-counter'),
    load: () => t().then((m) => m.WordCounter),
  },
  {
    slug: 'character-counter',
    name: 'Character Counter',
    shortDescription:
      'Count characters with and without spaces and check limits for SMS, X and meta tags.',
    keywords: [
      'character count',
      'character counter',
      'letters',
      'sms length',
      'tweet length',
      'text',
    ],
    aliases: ['letter counter', 'char count'],
    icon: 'type',
    localOnly: true,
    relatedTools: others(COUNT, 'character-counter'),
    load: () => t().then((m) => m.CharacterCounter),
  },
  {
    slug: 'sentence-counter',
    name: 'Sentence Counter',
    shortDescription: 'Count sentences and average sentence length to improve readability.',
    keywords: ['sentence count', 'sentence counter', 'readability', 'text'],
    aliases: ['count sentences'],
    icon: 'align',
    localOnly: true,
    relatedTools: others(COUNT, 'sentence-counter'),
    load: () => t().then((m) => m.SentenceCounter),
  },
  {
    slug: 'paragraph-counter',
    name: 'Paragraph Counter',
    shortDescription: 'Count paragraphs and average paragraph length in any text.',
    keywords: ['paragraph count', 'paragraph counter', 'text'],
    aliases: ['count paragraphs'],
    icon: 'align',
    localOnly: true,
    relatedTools: others(COUNT, 'paragraph-counter'),
    load: () => t().then((m) => m.ParagraphCounter),
  },
  {
    slug: 'reading-time-calculator',
    name: 'Reading Time Calculator',
    shortDescription: 'Estimate how long an article takes to read or a script takes to speak.',
    keywords: ['reading time', 'read time', 'speaking time', 'speech length', 'blog', 'text'],
    aliases: ['how long to read', 'speech timer'],
    icon: 'book',
    localOnly: true,
    relatedTools: others(COUNT, 'reading-time-calculator'),
    load: () => t().then((m) => m.ReadingTimeCalculator),
  },
  {
    slug: 'case-converter',
    name: 'Case Converter',
    shortDescription:
      'Convert text to sentence, title, upper, lower, camel, snake, kebab and more.',
    keywords: ['case converter', 'change case', 'camelcase', 'snake case', 'title case', 'text'],
    aliases: ['text case changer', 'convert case'],
    icon: 'case',
    isPopular: true,
    localOnly: true,
    relatedTools: others(CASE, 'case-converter', ['slug-generator']),
    load: () => t().then((m) => m.CaseConverter),
  },
  {
    slug: 'uppercase-converter',
    name: 'Uppercase Converter',
    shortDescription: 'Convert text to UPPERCASE instantly.',
    keywords: ['uppercase', 'capital letters', 'all caps', 'upper case', 'text'],
    aliases: ['to uppercase', 'caps converter'],
    icon: 'case',
    localOnly: true,
    relatedTools: others(CASE, 'uppercase-converter'),
    load: () => t().then((m) => m.UppercaseConverter),
  },
  {
    slug: 'lowercase-converter',
    name: 'Lowercase Converter',
    shortDescription: 'Convert text to lowercase instantly.',
    keywords: ['lowercase', 'small letters', 'lower case', 'text'],
    aliases: ['to lowercase'],
    icon: 'case',
    localOnly: true,
    relatedTools: others(CASE, 'lowercase-converter'),
    load: () => t().then((m) => m.LowercaseConverter),
  },
  {
    slug: 'title-case-converter',
    name: 'Title Case Converter',
    shortDescription: 'Capitalise headings properly, keeping small words and acronyms right.',
    keywords: ['title case', 'headline case', 'capitalize title', 'heading', 'text'],
    aliases: ['headline capitalization'],
    icon: 'case',
    localOnly: true,
    relatedTools: others(CASE, 'title-case-converter', ['slug-generator']),
    load: () => t().then((m) => m.TitleCaseConverter),
  },
  {
    slug: 'remove-duplicate-lines',
    name: 'Remove Duplicate Lines',
    shortDescription: 'Delete repeated lines from lists, keeping the first occurrence.',
    keywords: ['remove duplicates', 'duplicate lines', 'unique lines', 'dedupe', 'list', 'text'],
    aliases: ['dedupe list', 'unique list'],
    icon: 'list',
    localOnly: true,
    relatedTools: ['text-sorter', 'remove-extra-spaces', 'line-counter', 'text-cleaner'],
    load: () => t().then((m) => m.RemoveDuplicateLines),
  },
  {
    slug: 'remove-extra-spaces',
    name: 'Remove Extra Spaces',
    shortDescription: 'Collapse multiple spaces, trim lines and tidy blank lines.',
    keywords: ['remove spaces', 'extra spaces', 'whitespace', 'trim', 'text'],
    aliases: ['space remover', 'remove whitespace'],
    icon: 'eraser',
    localOnly: true,
    relatedTools: ['text-cleaner', 'remove-duplicate-lines', 'find-and-replace'],
    load: () => t().then((m) => m.RemoveExtraSpaces),
  },
  {
    slug: 'text-sorter',
    name: 'Text Sorter',
    shortDescription: 'Sort lines alphabetically, naturally, by length, or shuffle them.',
    keywords: ['sort lines', 'alphabetical order', 'sort list', 'shuffle', 'text'],
    aliases: ['alphabetize', 'sort alphabetically'],
    icon: 'list',
    localOnly: true,
    relatedTools: ['remove-duplicate-lines', 'text-reverser', 'random-picker'],
    load: () => t().then((m) => m.TextSorter),
  },
  {
    slug: 'text-reverser',
    name: 'Text Reverser',
    shortDescription: 'Reverse characters, words or lines — Unicode and emoji safe.',
    keywords: ['reverse text', 'backwards text', 'mirror text', 'reverse words', 'text'],
    aliases: ['backwards writing'],
    icon: 'swap',
    localOnly: true,
    relatedTools: ['text-sorter', 'case-converter'],
    load: () => t().then((m) => m.TextReverser),
  },
  {
    slug: 'text-cleaner',
    name: 'Text Cleaner',
    shortDescription:
      'Strip HTML, emoji, smart quotes, invisible characters, URLs and more from text.',
    keywords: ['clean text', 'strip html', 'remove emoji', 'plain text', 'sanitize', 'text'],
    aliases: ['plain text converter', 'remove formatting'],
    icon: 'eraser',
    localOnly: true,
    relatedTools: ['remove-extra-spaces', 'find-and-replace', 'html-entity-decoder'],
    load: () => t().then((m) => m.TextCleaner),
  },
  {
    slug: 'slug-generator',
    name: 'Slug Generator',
    shortDescription: 'Turn titles into clean, SEO-friendly URL slugs.',
    keywords: ['slug', 'url slug', 'permalink', 'seo url', 'slugify'],
    aliases: ['slugify', 'permalink generator'],
    icon: 'link',
    alsoIn: ['developer'],
    localOnly: true,
    relatedTools: ['case-converter', 'url-encoder', 'title-case-converter'],
    load: () => t().then((m) => m.SlugGenerator),
  },
  {
    slug: 'find-and-replace',
    name: 'Find & Replace',
    shortDescription: 'Find and replace text with match case, whole-word and regex options.',
    keywords: ['find and replace', 'search replace', 'replace text', 'regex replace', 'text'],
    aliases: ['find replace', 'bulk replace'],
    icon: 'replace',
    localOnly: true,
    relatedTools: ['regex-tester', 'text-cleaner', 'text-compare'],
    load: () => t().then((m) => m.FindAndReplace),
  },
  {
    slug: 'text-compare',
    name: 'Text Compare',
    shortDescription: 'Compare two texts line by line and highlight what was added or removed.',
    keywords: ['text compare', 'diff', 'compare text', 'difference checker', 'text'],
    aliases: ['diff checker', 'compare documents'],
    icon: 'compare',
    localOnly: true,
    relatedTools: ['find-and-replace', 'remove-duplicate-lines', 'word-counter'],
    load: () => import('./TextCompare').then((m) => m.default),
  },
  {
    slug: 'line-counter',
    name: 'Line Counter',
    shortDescription: 'Count total, non-empty and blank lines and find the longest line.',
    keywords: ['line count', 'count lines', 'lines of code', 'loc', 'text'],
    aliases: ['count lines of text'],
    icon: 'list',
    localOnly: true,
    relatedTools: others(COUNT, 'line-counter'),
    load: () => t().then((m) => m.LineCounter),
  },
]);
