import { defineCategory } from '../define';

const d = () => import('./tools');

export const dateTimeTools = defineCategory('date-time', [
  {
    slug: 'age-calculator',
    name: 'Age Calculator',
    shortDescription:
      'Calculate exact age in years, months and days from date of birth, with next birthday.',
    keywords: ['age', 'date of birth', 'dob', 'birthday', 'how old', 'years old'],
    aliases: ['age from dob', 'how old am i', 'birthday calculator', 'age calc'],
    icon: 'calendar',
    alsoIn: ['education', 'everyday'],
    isPopular: true,
    isFeatured: true,
    shareSubject: 'age',
    relatedTools: [
      'date-difference-calculator',
      'days-between-dates',
      'countdown-calculator',
      'leap-year-checker',
    ],
    load: () => d().then((m) => m.AgeCalculator),
  },
  {
    slug: 'date-difference-calculator',
    name: 'Date Difference Calculator',
    shortDescription:
      'Find the difference between two dates in years, months, days, weeks and hours.',
    keywords: ['date difference', 'between dates', 'duration', 'how long', 'years months days'],
    aliases: ['date duration', 'time between dates'],
    icon: 'calendar',
    relatedTools: [
      'days-between-dates',
      'age-calculator',
      'working-days-calculator',
      'date-calculator',
    ],
    load: () => d().then((m) => m.DateDifferenceCalculator),
  },
  {
    slug: 'days-between-dates',
    name: 'Days Between Dates',
    shortDescription: 'Count the number of days, weekdays and weekend days between two dates.',
    keywords: ['days between dates', 'number of days', 'count days', 'day counter', 'date'],
    aliases: ['how many days', 'days until', 'day count'],
    icon: 'calendar',
    relatedTools: ['date-difference-calculator', 'working-days-calculator', 'add-days-calculator'],
    load: () => d().then((m) => m.DaysBetweenDatesCalculator),
  },
  {
    slug: 'add-days-calculator',
    name: 'Add Days Calculator',
    shortDescription: 'Add days, weeks, months or years to a date and get the resulting date.',
    keywords: ['add days', 'date plus days', 'future date', 'after days', 'date'],
    aliases: ['days from today', 'date after n days', '90 days from today'],
    icon: 'calendarClock',
    relatedTools: ['subtract-days-calculator', 'business-days-calculator', 'date-calculator'],
    load: () => d().then((m) => m.AddDaysCalculator),
  },
  {
    slug: 'subtract-days-calculator',
    name: 'Subtract Days Calculator',
    shortDescription: 'Subtract days, weeks, months or years from a date to find an earlier date.',
    keywords: ['subtract days', 'date minus days', 'past date', 'days before', 'date'],
    aliases: ['days ago', 'date before n days'],
    icon: 'calendarClock',
    relatedTools: ['add-days-calculator', 'business-days-calculator', 'date-calculator'],
    load: () => d().then((m) => m.SubtractDaysCalculator),
  },
  {
    slug: 'working-days-calculator',
    name: 'Working Days Calculator',
    shortDescription: 'Count working days between two dates, excluding weekly offs and holidays.',
    keywords: ['working days', 'weekdays', 'excluding weekends', 'holidays', 'office days'],
    aliases: ['work days between dates', 'weekday counter'],
    icon: 'briefcase',
    relatedTools: ['business-days-calculator', 'days-between-dates', 'notice-period-calculator'],
    load: () => d().then((m) => m.WorkingDaysCalculator),
  },
  {
    slug: 'business-days-calculator',
    name: 'Business Days Calculator',
    shortDescription: 'Add or subtract business days from a date, skipping weekends and holidays.',
    keywords: ['business days', 'working days', 'add business days', 'sla', 'delivery date'],
    aliases: ['business day adder', 'next working day'],
    icon: 'briefcase',
    relatedTools: ['working-days-calculator', 'add-days-calculator', 'notice-period-calculator'],
    load: () => d().then((m) => m.BusinessDaysCalculator),
  },
  {
    slug: 'leap-year-checker',
    name: 'Leap Year Checker',
    shortDescription:
      'Check whether a year is a leap year and find the next and previous leap years.',
    keywords: ['leap year', '366 days', 'february 29', 'calendar'],
    aliases: ['is it a leap year'],
    icon: 'calendar',
    relatedTools: ['age-calculator', 'week-number-calculator', 'date-difference-calculator'],
    load: () => d().then((m) => m.LeapYearChecker),
  },
  {
    slug: 'week-number-calculator',
    name: 'Week Number Calculator',
    shortDescription: 'Find the ISO week number, day of the year and quarter for any date.',
    keywords: ['week number', 'iso week', 'which week', 'day of year', 'quarter'],
    aliases: ['current week number', 'week of year'],
    icon: 'calendar',
    relatedTools: ['leap-year-checker', 'date-calculator', 'days-between-dates'],
    load: () => d().then((m) => m.WeekNumberCalculator),
  },
  {
    slug: 'countdown-calculator',
    name: 'Countdown Calculator',
    shortDescription: 'Live countdown in days, hours, minutes and seconds to any date and time.',
    keywords: ['countdown', 'timer', 'days left', 'time until', 'event'],
    aliases: ['countdown timer', 'days until event', 'new year countdown'],
    icon: 'hourglass',
    relatedTools: ['exam-countdown', 'days-between-dates', 'age-calculator'],
    load: () => import('./Countdown').then((m) => m.default),
  },
  {
    slug: 'time-duration-calculator',
    name: 'Time Duration Calculator',
    shortDescription:
      'Calculate hours and minutes between two times, minus breaks, for timesheets.',
    keywords: [
      'time duration',
      'hours between times',
      'timesheet',
      'work hours',
      'time difference',
    ],
    aliases: ['hours calculator', 'time between two times', 'shift hours'],
    icon: 'clock',
    relatedTools: ['time-converter', 'hourly-salary-calculator', 'sleep-calculator'],
    load: () => d().then((m) => m.TimeDurationCalculator),
  },
  {
    slug: 'time-zone-converter',
    name: 'Time Zone Converter',
    shortDescription: 'Convert time between IST and world time zones with daylight saving handled.',
    keywords: ['time zone', 'timezone', 'ist', 'est', 'pst', 'gmt', 'world clock', 'utc'],
    aliases: ['ist to est', 'ist to pst', 'world time', 'meeting planner'],
    icon: 'globe',
    relatedTools: ['unix-timestamp-converter', 'time-duration-calculator', 'timestamp-converter'],
    load: () => d().then((m) => m.TimeZoneConverter),
  },
  {
    slug: 'unix-timestamp-converter',
    name: 'Unix Timestamp Converter',
    shortDescription: 'Convert Unix epoch timestamps to dates and dates back to timestamps.',
    keywords: ['unix timestamp', 'epoch', 'epoch converter', 'timestamp', 'posix time'],
    aliases: ['epoch time converter', 'unix time'],
    icon: 'clock',
    alsoIn: ['developer'],
    localOnly: true,
    relatedTools: [
      'unix-timestamp-to-date',
      'date-to-unix-timestamp',
      'timestamp-converter',
      'time-zone-converter',
    ],
    load: () => d().then((m) => m.UnixTimestampConverter),
  },
  {
    slug: 'unix-timestamp-to-date',
    name: 'Unix Timestamp to Date',
    shortDescription:
      'Convert a Unix timestamp in seconds or milliseconds to a readable date in IST and UTC.',
    keywords: ['timestamp to date', 'epoch to date', 'unix to date', 'milliseconds to date'],
    aliases: ['epoch to human date'],
    icon: 'clock',
    localOnly: true,
    relatedTools: ['date-to-unix-timestamp', 'unix-timestamp-converter', 'timestamp-converter'],
    load: () => d().then((m) => m.UnixTimestampToDate),
  },
  {
    slug: 'date-to-unix-timestamp',
    name: 'Date to Unix Timestamp',
    shortDescription: 'Convert a date and time in any time zone to a Unix timestamp.',
    keywords: ['date to timestamp', 'date to epoch', 'to unix time', 'epoch'],
    aliases: ['human date to epoch'],
    icon: 'clock',
    localOnly: true,
    relatedTools: ['unix-timestamp-to-date', 'unix-timestamp-converter', 'time-zone-converter'],
    load: () => d().then((m) => m.DateToUnixTimestamp),
  },
]);
