import { defineCategory } from '../define';

const e = () => import('./tools');

export const everydayTools = defineCategory('everyday', [
  {
    slug: 'tip-calculator',
    name: 'Tip Calculator',
    shortDescription: 'Calculate the tip and each person’s share of a restaurant bill.',
    keywords: ['tip', 'gratuity', 'restaurant bill', 'waiter tip', 'split'],
    aliases: ['how much to tip', 'tip amount'],
    icon: 'utensils',
    relatedTools: ['split-bill-calculator', 'discount-calculator', 'percentage-calculator'],
    load: () => e().then((m) => m.TipCalculator),
  },
  {
    slug: 'split-bill-calculator',
    name: 'Split Bill Calculator',
    shortDescription:
      'Split a bill equally or by what each person ordered, including GST, service charge and tip.',
    keywords: ['split bill', 'share bill', 'divide bill', 'restaurant', 'friends', 'trip expenses'],
    aliases: ['bill splitter', 'expense splitter'],
    icon: 'users',
    isPopular: true,
    relatedTools: ['tip-calculator', 'fuel-cost-calculator', 'gst-calculator'],
    load: () => e().then((m) => m.SplitBillCalculator),
  },
  {
    slug: 'fuel-cost-calculator',
    name: 'Fuel Cost Calculator',
    shortDescription: 'Estimate petrol or diesel cost for a trip and split it among passengers.',
    keywords: ['fuel cost', 'petrol cost', 'diesel cost', 'trip cost', 'road trip', 'travel'],
    aliases: ['petrol calculator', 'trip fuel cost'],
    icon: 'fuel',
    isPopular: true,
    relatedTools: [
      'fuel-mileage-calculator',
      'fuel-economy-converter',
      'split-bill-calculator',
      'car-loan-emi-calculator',
    ],
    load: () => e().then((m) => m.FuelCostCalculator),
  },
  {
    slug: 'fuel-mileage-calculator',
    name: 'Fuel Mileage Calculator',
    shortDescription: 'Calculate your vehicle’s real mileage (km/L) and running cost per km.',
    keywords: ['mileage', 'fuel efficiency', 'km per litre', 'kmpl', 'bike mileage', 'car mileage'],
    aliases: ['average calculator', 'kmpl calculator'],
    icon: 'gauge',
    relatedTools: ['fuel-cost-calculator', 'fuel-economy-converter'],
    load: () => e().then((m) => m.FuelMileageCalculator),
  },
  {
    slug: 'electricity-cost-calculator',
    name: 'Electricity Cost Calculator',
    shortDescription:
      'Estimate electricity units and bill for an AC, geyser, fridge or any appliance.',
    keywords: [
      'electricity bill',
      'electricity cost',
      'units',
      'kwh',
      'ac bill',
      'power consumption',
    ],
    aliases: ['electricity bill calculator', 'power consumption calculator', 'unit calculator'],
    icon: 'zap',
    isPopular: true,
    relatedTools: ['energy-converter', 'power-converter'],
    load: () => e().then((m) => m.ElectricityCostCalculator),
  },
  {
    slug: 'cooking-unit-converter',
    name: 'Cooking Unit Converter',
    shortDescription:
      'Convert cups, tablespoons, grams and katori for atta, rice, sugar, ghee and more.',
    keywords: ['cooking', 'recipe', 'cups to grams', 'tablespoon', 'baking', 'kitchen'],
    aliases: ['cups to grams', 'recipe converter', 'baking converter'],
    icon: 'utensils',
    alsoIn: ['converters'],
    relatedTools: ['weight-converter', 'volume-converter', 'temperature-converter'],
    load: () => e().then((m) => m.CookingUnitConverter),
  },
  {
    slug: 'random-picker',
    name: 'Random Picker',
    shortDescription: 'Pick random names or options from a list — for draws, turns and giveaways.',
    keywords: ['random picker', 'random name', 'lucky draw', 'wheel', 'choose for me', 'raffle'],
    aliases: ['random name picker', 'lucky draw', 'decision maker'],
    icon: 'dice',
    localOnly: true,
    relatedTools: ['random-number-generator', 'text-sorter', 'password-generator'],
    load: () => e().then((m) => m.RandomPicker),
  },
  {
    slug: 'date-calculator',
    name: 'Date Calculator',
    shortDescription:
      'Find the difference between two dates or add and subtract days, weeks, months and years.',
    keywords: ['date calculator', 'date difference', 'add days', 'subtract days', 'calendar'],
    aliases: ['calculate date'],
    icon: 'calendar',
    alsoIn: ['date-time'],
    relatedTools: [
      'date-difference-calculator',
      'add-days-calculator',
      'age-calculator',
      'days-between-dates',
    ],
    load: () => e().then((m) => m.DateCalculator),
  },
  {
    slug: 'sleep-calculator',
    name: 'Sleep Calculator',
    shortDescription: 'Find the best time to go to bed so you wake up at the end of a sleep cycle.',
    keywords: ['sleep', 'bedtime', 'sleep cycle', 'when to sleep', 'rem'],
    aliases: ['bedtime calculator', 'when should i sleep'],
    icon: 'moon',
    disclaimer: 'health',
    relatedTools: ['wake-up-time-calculator', 'time-duration-calculator'],
    load: () => e().then((m) => m.SleepCalculator),
  },
  {
    slug: 'wake-up-time-calculator',
    name: 'Wake-up Time Calculator',
    shortDescription: 'Find the best time to wake up based on when you go to sleep.',
    keywords: ['wake up time', 'alarm', 'sleep cycle', 'when to wake up'],
    aliases: ['alarm time calculator'],
    icon: 'alarm',
    disclaimer: 'health',
    relatedTools: ['sleep-calculator', 'time-duration-calculator'],
    load: () => e().then((m) => m.WakeUpTimeCalculator),
  },
]);
