import { defineCategory } from '../define';
import type { ToolInput } from '@/types/tool';

const d = () => import('./tools');

type DevInput = Omit<ToolInput, 'localOnly'>;
const dev = (t: DevInput): ToolInput => ({ localOnly: true, ...t });

const JSON_REL = [
  'json-formatter',
  'json-validator',
  'json-minifier',
  'json-beautifier',
  'yaml-formatter',
  'xml-formatter',
];

export const developerTools = defineCategory('developer', [
  dev({
    slug: 'json-formatter',
    name: 'JSON Formatter',
    shortDescription:
      'Format and indent JSON with 2 spaces, 4 spaces or tabs, and optionally sort keys.',
    keywords: [
      'json',
      'json formatter',
      'format json',
      'pretty print',
      'indent json',
      'api response',
    ],
    aliases: ['json pretty print', 'json format online', 'json viewer'],
    icon: 'json',
    isPopular: true,
    isFeatured: true,
    relatedTools: JSON_REL.filter((s) => s !== 'json-formatter'),
    load: () => d().then((m) => m.JsonFormatter),
  }),
  dev({
    slug: 'json-validator',
    name: 'JSON Validator',
    shortDescription: 'Validate JSON and pinpoint syntax errors by line and column.',
    keywords: ['json validator', 'validate json', 'json lint', 'json error', 'json'],
    aliases: ['jsonlint', 'check json'],
    icon: 'json',
    relatedTools: JSON_REL.filter((s) => s !== 'json-validator'),
    load: () => d().then((m) => m.JsonValidator),
  }),
  dev({
    slug: 'json-minifier',
    name: 'JSON Minifier',
    shortDescription: 'Minify JSON by removing whitespace to reduce payload size.',
    keywords: ['json minifier', 'minify json', 'compress json', 'json'],
    aliases: ['json compressor', 'compact json'],
    icon: 'json',
    relatedTools: JSON_REL.filter((s) => s !== 'json-minifier'),
    load: () => d().then((m) => m.JsonMinifier),
  }),
  dev({
    slug: 'json-beautifier',
    name: 'JSON Beautifier',
    shortDescription:
      'Beautify JSON with syntax highlighting, sorted keys and structure statistics.',
    keywords: ['json beautifier', 'beautify json', 'json highlight', 'json'],
    aliases: ['json colorizer'],
    icon: 'json',
    relatedTools: JSON_REL.filter((s) => s !== 'json-beautifier'),
    load: () => d().then((m) => m.JsonBeautifier),
  }),
  dev({
    slug: 'base64-encoder',
    name: 'Base64 Encoder',
    shortDescription: 'Encode text to Base64 or URL-safe Base64 with full Unicode support.',
    keywords: ['base64', 'base64 encode', 'encode', 'base64url', 'btoa'],
    aliases: ['text to base64', 'base64 encoding'],
    icon: 'binary',
    relatedTools: ['base64-decoder', 'url-encoder', 'hash-generator', 'jwt-decoder'],
    load: () => d().then((m) => m.Base64Encoder),
  }),
  dev({
    slug: 'base64-decoder',
    name: 'Base64 Decoder',
    shortDescription: 'Decode Base64 or Base64URL back to text, or view binary as hex.',
    keywords: ['base64 decode', 'decode base64', 'atob', 'base64'],
    aliases: ['base64 to text'],
    icon: 'binary',
    relatedTools: ['base64-encoder', 'url-decoder', 'jwt-decoder'],
    load: () => d().then((m) => m.Base64Decoder),
  }),
  dev({
    slug: 'url-encoder',
    name: 'URL Encoder',
    shortDescription: 'Percent-encode text or URLs for safe use in query strings.',
    keywords: ['url encode', 'percent encoding', 'encodeuricomponent', 'query string', 'url'],
    aliases: ['urlencode', 'uri encoder'],
    icon: 'link',
    relatedTools: ['url-decoder', 'base64-encoder', 'html-entity-encoder'],
    load: () => d().then((m) => m.UrlEncoder),
  }),
  dev({
    slug: 'url-decoder',
    name: 'URL Decoder',
    shortDescription: 'Decode percent-encoded URLs and inspect their query parameters.',
    keywords: ['url decode', 'decode url', 'percent decoding', 'query parameters', 'url'],
    aliases: ['urldecode', 'uri decoder'],
    icon: 'link',
    relatedTools: ['url-encoder', 'base64-decoder', 'html-entity-decoder'],
    load: () => d().then((m) => m.UrlDecoder),
  }),
  dev({
    slug: 'uuid-generator',
    name: 'UUID Generator',
    shortDescription: 'Generate random v4 or time-ordered v7 UUIDs in bulk.',
    keywords: ['uuid', 'guid', 'uuid v4', 'uuid v7', 'unique id', 'generator'],
    aliases: ['guid generator', 'random uuid'],
    icon: 'fingerprint',
    relatedTools: ['password-generator', 'hash-generator', 'random-number-generator'],
    load: () => d().then((m) => m.UuidGenerator),
  }),
  dev({
    slug: 'password-generator',
    name: 'Password Generator',
    shortDescription: 'Generate strong random passwords with the characters you choose.',
    keywords: ['password', 'password generator', 'strong password', 'random password', 'secure'],
    aliases: ['generate password', 'random password generator'],
    icon: 'key',
    alsoIn: ['everyday'],
    isPopular: true,
    relatedTools: ['uuid-generator', 'hash-generator', 'random-picker'],
    load: () => d().then((m) => m.PasswordGenerator),
  }),
  dev({
    slug: 'hash-generator',
    name: 'Hash Generator',
    shortDescription: 'Generate MD5, SHA-1, SHA-256, SHA-384 and SHA-512 hashes or HMACs.',
    keywords: ['hash', 'md5', 'sha256', 'sha1', 'sha512', 'hmac', 'checksum'],
    aliases: ['sha256 generator', 'md5 generator', 'checksum calculator'],
    icon: 'hash',
    relatedTools: ['base64-encoder', 'jwt-encoder', 'uuid-generator'],
    load: () => d().then((m) => m.HashGenerator),
  }),
  dev({
    slug: 'jwt-decoder',
    name: 'JWT Decoder',
    shortDescription: 'Decode JSON Web Tokens, read claims and expiry, and verify HMAC signatures.',
    keywords: ['jwt', 'json web token', 'decode jwt', 'bearer token', 'claims'],
    aliases: ['jwt parser', 'jwt debugger', 'jwt.io'],
    icon: 'lock',
    relatedTools: ['jwt-encoder', 'base64-decoder', 'unix-timestamp-to-date'],
    load: () => d().then((m) => m.JwtDecoder),
  }),
  dev({
    slug: 'jwt-encoder',
    name: 'JWT Encoder',
    shortDescription: 'Create HS256, HS384 or HS512 signed JWTs from a JSON payload.',
    keywords: ['jwt encoder', 'create jwt', 'sign jwt', 'hs256', 'json web token'],
    aliases: ['jwt generator'],
    icon: 'lock',
    relatedTools: ['jwt-decoder', 'hash-generator', 'date-to-unix-timestamp'],
    load: () => d().then((m) => m.JwtEncoder),
  }),
  dev({
    slug: 'regex-tester',
    name: 'Regex Tester',
    shortDescription:
      'Test JavaScript regular expressions with live match highlighting, groups and replace.',
    keywords: ['regex', 'regular expression', 'regex tester', 'pattern', 'match'],
    aliases: ['regexp tester', 'regex101'],
    icon: 'regex',
    relatedTools: ['find-and-replace', 'text-compare', 'json-validator'],
    load: () => import('./RegexTester').then((m) => m.default),
  }),
  dev({
    slug: 'sql-formatter',
    name: 'SQL Formatter',
    shortDescription: 'Format SQL queries for MySQL, PostgreSQL, SQL Server, Oracle and more.',
    keywords: ['sql', 'sql formatter', 'format sql', 'beautify sql', 'query'],
    aliases: ['sql beautifier', 'pretty sql'],
    icon: 'database',
    relatedTools: ['sql-minifier', 'json-formatter', 'xml-formatter'],
    load: () => d().then((m) => m.SqlFormatter),
  }),
  dev({
    slug: 'sql-minifier',
    name: 'SQL Minifier',
    shortDescription:
      'Minify SQL by removing comments and extra whitespace while keeping strings intact.',
    keywords: ['sql minifier', 'minify sql', 'compress sql', 'sql'],
    aliases: ['sql compressor'],
    icon: 'database',
    relatedTools: ['sql-formatter', 'json-minifier'],
    load: () => d().then((m) => m.SqlMinifier),
  }),
  dev({
    slug: 'html-formatter',
    name: 'HTML Formatter',
    shortDescription: 'Format and indent HTML, including embedded CSS and JavaScript.',
    keywords: ['html', 'html formatter', 'beautify html', 'format html', 'markup'],
    aliases: ['html beautifier', 'html prettify'],
    icon: 'fileCode',
    relatedTools: ['css-formatter', 'javascript-formatter', 'html-entity-encoder'],
    load: () => d().then((m) => m.HtmlFormatter),
  }),
  dev({
    slug: 'css-formatter',
    name: 'CSS Formatter',
    shortDescription: 'Format or minify CSS stylesheets.',
    keywords: ['css', 'css formatter', 'beautify css', 'minify css', 'stylesheet'],
    aliases: ['css beautifier', 'css minifier'],
    icon: 'palette',
    relatedTools: ['html-formatter', 'javascript-formatter', 'color-converter'],
    load: () => d().then((m) => m.CssFormatter),
  }),
  dev({
    slug: 'javascript-formatter',
    name: 'JavaScript Formatter',
    shortDescription: 'Format JavaScript code consistently with Prettier.',
    keywords: ['javascript', 'js formatter', 'beautify js', 'format javascript', 'prettier'],
    aliases: ['js beautifier', 'js prettify'],
    icon: 'code',
    relatedTools: ['typescript-formatter', 'html-formatter', 'json-formatter'],
    load: () => d().then((m) => m.JavaScriptFormatter),
  }),
  dev({
    slug: 'typescript-formatter',
    name: 'TypeScript Formatter',
    shortDescription: 'Format TypeScript code consistently with Prettier.',
    keywords: ['typescript', 'ts formatter', 'format typescript', 'prettier'],
    aliases: ['ts beautifier'],
    icon: 'code',
    relatedTools: ['javascript-formatter', 'json-formatter'],
    load: () => d().then((m) => m.TypeScriptFormatter),
  }),
  dev({
    slug: 'xml-formatter',
    name: 'XML Formatter',
    shortDescription: 'Pretty-print or minify XML documents.',
    keywords: ['xml', 'xml formatter', 'format xml', 'beautify xml', 'minify xml'],
    aliases: ['xml beautifier', 'xml pretty print'],
    icon: 'fileCode',
    relatedTools: ['xml-validator', 'json-formatter', 'yaml-formatter'],
    load: () => d().then((m) => m.XmlFormatter),
  }),
  dev({
    slug: 'xml-validator',
    name: 'XML Validator',
    shortDescription: 'Check whether XML is well-formed and find the first error.',
    keywords: ['xml validator', 'validate xml', 'well formed xml', 'xml'],
    aliases: ['xml checker', 'xml lint'],
    icon: 'fileCode',
    relatedTools: ['xml-formatter', 'json-validator'],
    load: () => d().then((m) => m.XmlValidator),
  }),
  dev({
    slug: 'yaml-formatter',
    name: 'YAML Formatter',
    shortDescription: 'Format and validate YAML such as Docker Compose, Kubernetes and CI files.',
    keywords: ['yaml', 'yml', 'yaml formatter', 'format yaml', 'docker compose', 'kubernetes'],
    aliases: ['yaml beautifier', 'yaml validator'],
    icon: 'align',
    relatedTools: ['json-formatter', 'xml-formatter'],
    load: () => d().then((m) => m.YamlFormatter),
  }),
  dev({
    slug: 'timestamp-converter',
    name: 'Timestamp Converter',
    shortDescription:
      'Convert between Unix time, ISO 8601, RFC 2822 and readable dates in IST and UTC.',
    keywords: ['timestamp', 'iso 8601', 'rfc 2822', 'epoch', 'date format', 'unix'],
    aliases: ['iso date converter', 'date format converter'],
    icon: 'clock',
    relatedTools: ['unix-timestamp-converter', 'unix-timestamp-to-date', 'time-zone-converter'],
    load: () => d().then((m) => m.TimestampConverter),
  }),
  dev({
    slug: 'cron-expression-generator',
    name: 'Cron Expression Generator',
    shortDescription:
      'Build cron schedules visually, read them in plain English and preview the next runs.',
    keywords: ['cron', 'crontab', 'cron expression', 'schedule', 'cron job'],
    aliases: ['crontab generator', 'cron builder', 'cron explainer'],
    icon: 'calendarClock',
    relatedTools: ['timestamp-converter', 'time-zone-converter'],
    load: () => import('./CronGenerator').then((m) => m.default),
  }),
  dev({
    slug: 'color-converter',
    name: 'Color Converter',
    shortDescription: 'Convert colours between HEX, RGB, HSL, HSV and CMYK and check contrast.',
    keywords: ['color', 'colour', 'hex to rgb', 'rgb to hex', 'hsl', 'cmyk', 'contrast'],
    aliases: ['colour converter', 'hex to rgb', 'color picker'],
    icon: 'palette',
    relatedTools: ['css-formatter', 'html-formatter'],
    load: () => import('./ColorConverter').then((m) => m.default),
  }),
  dev({
    slug: 'lorem-ipsum-generator',
    name: 'Lorem Ipsum Generator',
    shortDescription: 'Generate lorem ipsum placeholder paragraphs, sentences or words.',
    keywords: ['lorem ipsum', 'placeholder text', 'dummy text', 'filler text'],
    aliases: ['dummy text generator', 'lipsum'],
    icon: 'align',
    alsoIn: ['text'],
    relatedTools: ['word-counter', 'character-counter', 'html-formatter'],
    load: () => d().then((m) => m.LoremIpsumGenerator),
  }),
  dev({
    slug: 'user-agent-parser',
    name: 'User Agent Parser',
    shortDescription: 'Parse a user agent string into browser, OS, device and engine.',
    keywords: ['user agent', 'ua parser', 'browser detection', 'device detection', 'useragent'],
    aliases: ['what is my browser', 'ua string'],
    icon: 'monitor',
    relatedTools: ['ip-address-information-tool', 'url-decoder', 'timestamp-converter'],
    load: () => d().then((m) => m.UserAgentParser),
  }),
  {
    slug: 'ip-address-information-tool',
    name: 'IP Address Information Tool',
    shortDescription:
      'Analyse any IPv4 or IPv6 address or subnet: type, binary form and CIDR range details.',
    keywords: ['ip address', 'subnet', 'cidr', 'ipv4', 'ipv6', 'network', 'private ip'],
    aliases: ['subnet calculator', 'ip calculator', 'cidr calculator'],
    icon: 'network',
    localOnly: true,
    relatedTools: ['user-agent-parser', 'url-decoder'],
    load: () => import('./IpTool').then((m) => m.default),
  },
  dev({
    slug: 'html-entity-encoder',
    name: 'HTML Entity Encoder',
    shortDescription: 'Escape special characters as HTML entities to display code safely.',
    keywords: ['html entities', 'html encode', 'escape html', '&amp;', 'entity'],
    aliases: ['html escape'],
    icon: 'code',
    relatedTools: ['html-entity-decoder', 'url-encoder', 'html-formatter'],
    load: () => d().then((m) => m.HtmlEntityEncoder),
  }),
  dev({
    slug: 'html-entity-decoder',
    name: 'HTML Entity Decoder',
    shortDescription: 'Convert HTML entities like &amp; and &#8377; back to readable characters.',
    keywords: ['html entities', 'html decode', 'unescape html', 'entity decoder'],
    aliases: ['html unescape'],
    icon: 'code',
    relatedTools: ['html-entity-encoder', 'url-decoder'],
    load: () => d().then((m) => m.HtmlEntityDecoder),
  }),
]);
