import { defineCategory } from '../define';

const h = () => import('./tools');

export const healthTools = defineCategory('health', [
  {
    slug: 'bmi-calculator',
    name: 'BMI Calculator',
    shortDescription:
      'Calculate Body Mass Index with both WHO and Asian-Indian categories and your healthy weight range.',
    keywords: [
      'bmi',
      'body mass index',
      'weight',
      'obesity',
      'overweight',
      'healthy weight',
      'health',
    ],
    aliases: ['bmi check', 'body mass', 'am i overweight'],
    icon: 'activity',
    isPopular: true,
    isFeatured: true,
    disclaimer: 'health',
    shareSubject: 'BMI',
    relatedTools: [
      'ideal-weight-calculator',
      'body-fat-calculator',
      'bmr-calculator',
      'calorie-calculator',
      'height-converter',
    ],
    load: () => h().then((m) => m.BmiCalculator),
  },
  {
    slug: 'bmr-calculator',
    name: 'BMR Calculator',
    shortDescription:
      'Estimate your basal metabolic rate with Mifflin-St Jeor, Harris-Benedict or Katch-McArdle.',
    keywords: ['bmr', 'basal metabolic rate', 'metabolism', 'calories at rest', 'health'],
    aliases: ['metabolic rate', 'resting calories'],
    icon: 'flame',
    disclaimer: 'health',
    relatedTools: ['tdee-calculator', 'calorie-calculator', 'bmi-calculator', 'macro-calculator'],
    load: () => h().then((m) => m.BmrCalculator),
  },
  {
    slug: 'tdee-calculator',
    name: 'TDEE Calculator',
    shortDescription: 'Find your total daily energy expenditure — the calories you burn each day.',
    keywords: ['tdee', 'total daily energy expenditure', 'maintenance calories', 'calories burned'],
    aliases: ['maintenance calorie calculator'],
    icon: 'flame',
    disclaimer: 'health',
    relatedTools: [
      'bmr-calculator',
      'calorie-calculator',
      'calorie-deficit-calculator',
      'macro-calculator',
    ],
    load: () => h().then((m) => m.TdeeCalculator),
  },
  {
    slug: 'calorie-calculator',
    name: 'Calorie Calculator',
    shortDescription: 'Work out daily calories to maintain, lose or gain weight.',
    keywords: ['calorie', 'calories', 'diet', 'weight loss', 'weight gain', 'daily calories'],
    aliases: ['how many calories', 'calorie intake', 'diet calculator'],
    icon: 'apple',
    isPopular: true,
    disclaimer: 'health',
    relatedTools: [
      'tdee-calculator',
      'macro-calculator',
      'calorie-deficit-calculator',
      'protein-calculator',
    ],
    load: () => h().then((m) => m.CalorieCalculator),
  },
  {
    slug: 'ideal-weight-calculator',
    name: 'Ideal Weight Calculator',
    shortDescription:
      'Find your ideal body weight using BMI ranges and the Devine, Robinson, Miller and Hamwi formulas.',
    keywords: ['ideal weight', 'healthy weight', 'ideal body weight', 'weight for height'],
    aliases: ['how much should i weigh', 'height weight chart'],
    icon: 'scale',
    disclaimer: 'health',
    relatedTools: ['bmi-calculator', 'body-fat-calculator', 'height-converter'],
    load: () => h().then((m) => m.IdealWeightCalculator),
  },
  {
    slug: 'body-fat-calculator',
    name: 'Body Fat Calculator',
    shortDescription: 'Estimate body fat percentage with the US Navy tape-measure method.',
    keywords: ['body fat', 'fat percentage', 'lean mass', 'navy method', 'fitness'],
    aliases: ['body fat percentage', 'fat calculator'],
    icon: 'dumbbell',
    disclaimer: 'health',
    relatedTools: ['bmi-calculator', 'ideal-weight-calculator', 'bmr-calculator'],
    load: () => h().then((m) => m.BodyFatCalculator),
  },
  {
    slug: 'water-intake-calculator',
    name: 'Water Intake Calculator',
    shortDescription:
      'Estimate how much water to drink daily based on weight, exercise and climate.',
    keywords: ['water intake', 'hydration', 'how much water', 'litres per day', 'drink water'],
    aliases: ['daily water', 'hydration calculator'],
    icon: 'droplets',
    disclaimer: 'health',
    relatedTools: ['calorie-calculator', 'bmi-calculator', 'volume-converter'],
    load: () => h().then((m) => m.WaterIntakeCalculator),
  },
  {
    slug: 'macro-calculator',
    name: 'Macro Calculator',
    shortDescription: 'Split daily calories into grams of protein, carbohydrates and fat.',
    keywords: ['macros', 'macronutrients', 'protein carbs fat', 'keto', 'diet plan'],
    aliases: ['macro split', 'iifym'],
    icon: 'pie',
    disclaimer: 'health',
    relatedTools: ['calorie-calculator', 'protein-calculator', 'tdee-calculator'],
    load: () => h().then((m) => m.MacroCalculator),
  },
  {
    slug: 'protein-calculator',
    name: 'Protein Calculator',
    shortDescription: 'Calculate your daily protein requirement for your weight and goal.',
    keywords: ['protein', 'protein intake', 'grams of protein', 'muscle gain', 'diet'],
    aliases: ['how much protein', 'protein per day'],
    icon: 'dumbbell',
    disclaimer: 'health',
    relatedTools: ['macro-calculator', 'calorie-calculator', 'body-fat-calculator'],
    load: () => h().then((m) => m.ProteinCalculator),
  },
  {
    slug: 'calorie-deficit-calculator',
    name: 'Calorie Deficit Calculator',
    shortDescription:
      'See how long it takes to reach your target weight with a daily calorie deficit.',
    keywords: ['calorie deficit', 'weight loss', 'lose weight', 'fat loss', 'diet'],
    aliases: ['weight loss calculator', 'how long to lose weight'],
    icon: 'target',
    disclaimer: 'health',
    relatedTools: ['tdee-calculator', 'calorie-calculator', 'macro-calculator'],
    load: () => h().then((m) => m.CalorieDeficitCalculator),
  },
  {
    slug: 'pregnancy-due-date-calculator',
    name: 'Pregnancy Due Date Calculator',
    shortDescription:
      'Estimate your due date from LMP, conception or IVF transfer date, with pregnancy week.',
    keywords: ['due date', 'pregnancy', 'edd', 'lmp', 'pregnancy week', 'trimester'],
    aliases: ['edd calculator', 'pregnancy calculator', 'delivery date'],
    icon: 'baby',
    disclaimer: 'health',
    relatedTools: ['age-calculator', 'days-between-dates', 'countdown-calculator'],
    load: () => h().then((m) => m.PregnancyDueDateCalculator),
  },
]);
