import { defineCategory } from '../define';

const t = () => import('./tools');
const GST_RELATED = [
  'gst-inclusive-calculator',
  'gst-exclusive-calculator',
  'gst-reverse-calculator',
  'gst-split-calculator',
  'gst-amount-calculator',
  'gst-invoice-calculator',
];

export const taxTools = defineCategory('tax', [
  {
    slug: 'gst-calculator',
    name: 'GST Calculator',
    shortDescription: 'Add or remove GST from any amount with CGST, SGST and IGST split.',
    keywords: ['gst', 'goods and services tax', 'gst calculation', 'cgst', 'sgst', 'igst', 'tax'],
    aliases: ['gst calc', 'add gst', 'remove gst', 'gst online'],
    icon: 'receipt',
    alsoIn: ['business'],
    isPopular: true,
    isFeatured: true,
    disclaimer: 'tax',
    shareSubject: 'GST',
    relatedTools: GST_RELATED,
    load: () => t().then((m) => m.GstCalculator),
  },
  {
    slug: 'gst-inclusive-calculator',
    name: 'GST Inclusive Calculator',
    shortDescription: 'Find the taxable value and GST inside a GST-inclusive price.',
    keywords: ['gst inclusive', 'inclusive of gst', 'mrp', 'remove gst', 'gst'],
    aliases: ['price including gst', 'extract gst'],
    icon: 'receipt',
    disclaimer: 'tax',
    relatedTools: [
      'gst-calculator',
      'gst-exclusive-calculator',
      'gst-reverse-calculator',
      'gst-split-calculator',
    ],
    load: () => t().then((m) => m.GstInclusiveCalculator),
  },
  {
    slug: 'gst-exclusive-calculator',
    name: 'GST Exclusive Calculator',
    shortDescription: 'Add GST to a price to get the final invoice amount.',
    keywords: ['gst exclusive', 'exclusive of gst', 'add gst', 'plus gst', 'gst'],
    aliases: ['price plus gst', 'price excluding gst'],
    icon: 'receipt',
    disclaimer: 'tax',
    relatedTools: [
      'gst-calculator',
      'gst-inclusive-calculator',
      'gst-amount-calculator',
      'gst-invoice-calculator',
    ],
    load: () => t().then((m) => m.GstExclusiveCalculator),
  },
  {
    slug: 'gst-reverse-calculator',
    name: 'GST Reverse Calculator',
    shortDescription:
      'Work backwards from a GST amount to the taxable value, or find the GST rate charged.',
    keywords: ['reverse gst', 'gst reverse', 'back calculate gst', 'gst rate', 'gst'],
    aliases: ['reverse gst calculation', 'find gst rate'],
    icon: 'swap',
    disclaimer: 'tax',
    relatedTools: ['gst-calculator', 'gst-inclusive-calculator', 'gst-split-calculator'],
    load: () => t().then((m) => m.GstReverseCalculator),
  },
  {
    slug: 'gst-split-calculator',
    name: 'GST Split Calculator',
    shortDescription: 'Split GST into CGST and SGST/UTGST, or IGST for inter-state supplies.',
    keywords: ['cgst', 'sgst', 'igst', 'utgst', 'gst split', 'gst breakup', 'gst'],
    aliases: ['cgst sgst calculator', 'igst calculator'],
    icon: 'split',
    disclaimer: 'tax',
    relatedTools: ['gst-calculator', 'gst-invoice-calculator', 'gst-amount-calculator'],
    load: () => t().then((m) => m.GstSplitCalculator),
  },
  {
    slug: 'gst-amount-calculator',
    name: 'GST Amount Calculator',
    shortDescription:
      'Quickly calculate the GST amount on a value and compare it across all GST slabs.',
    keywords: ['gst amount', 'gst on amount', 'gst slabs', 'gst rates', 'gst'],
    aliases: ['how much gst', 'gst for all rates'],
    icon: 'percent',
    disclaimer: 'tax',
    relatedTools: ['gst-calculator', 'gst-exclusive-calculator', 'gst-split-calculator'],
    load: () => t().then((m) => m.GstAmountCalculator),
  },
  {
    slug: 'income-tax-calculator',
    name: 'Income Tax Calculator',
    shortDescription:
      'Calculate income tax under the new and old regimes and see which saves more.',
    keywords: [
      'income tax',
      'tax',
      'new regime',
      'old regime',
      'itr',
      'tax slab',
      'salary tax',
      '87a',
    ],
    aliases: ['old vs new regime', 'tax calculator', 'income tax slab', 'how much tax'],
    icon: 'receipt',
    isPopular: true,
    isFeatured: true,
    disclaimer: 'tax',
    shareSubject: 'income tax',
    relatedTools: [
      'tax-saving-calculator',
      'hra-tax-exemption-calculator',
      'ctc-to-in-hand-salary-calculator',
      'capital-gains-calculator',
      'tds-calculator',
    ],
    load: () => t().then((m) => m.IncomeTaxCalculator),
  },
  {
    slug: 'hra-tax-exemption-calculator',
    name: 'HRA Tax Exemption Calculator',
    shortDescription: 'Calculate HRA exemption under Section 10(13A) and how much tax it saves.',
    keywords: ['hra exemption', 'section 10(13a)', 'hra', 'rent', 'tax saving', 'tax'],
    aliases: ['hra tax', 'hra exemption calculation'],
    icon: 'home',
    disclaimer: 'tax',
    relatedTools: ['hra-calculator', 'income-tax-calculator', 'tax-saving-calculator'],
    load: () => t().then((m) => m.HraTaxExemptionCalculator),
  },
  {
    slug: 'tds-calculator',
    name: 'TDS Calculator',
    shortDescription: 'Find TDS to deduct under sections 194A, 194C, 194J, 194H, 194I and more.',
    keywords: ['tds', 'tax deducted at source', '194j', '194c', '194a', '194i', '194h', 'tax'],
    aliases: ['tds rate', 'tds on rent', 'tds on professional fees'],
    icon: 'percent',
    alsoIn: ['business'],
    disclaimer: 'tax',
    relatedTools: ['income-tax-calculator', 'gst-calculator', 'fd-calculator'],
    load: () => t().then((m) => m.TdsCalculator),
  },
  {
    slug: 'capital-gains-calculator',
    name: 'Capital Gains Calculator',
    shortDescription: 'Calculate STCG and LTCG tax on shares, mutual funds, property and gold.',
    keywords: ['capital gains', 'ltcg', 'stcg', 'shares tax', 'property tax', 'indexation', 'tax'],
    aliases: ['ltcg tax', 'stcg tax', 'capital gain tax on property', 'share sale tax'],
    icon: 'lineChart',
    disclaimer: 'tax',
    relatedTools: ['income-tax-calculator', 'investment-return-calculator', 'cagr-calculator'],
    load: () => t().then((m) => m.CapitalGainsCalculator),
  },
  {
    slug: 'tax-saving-calculator',
    name: 'Tax Saving Calculator',
    shortDescription: 'See how much more tax you can save with 80C, 80D and NPS deductions.',
    keywords: ['tax saving', '80c', '80d', 'nps', 'save tax', 'deductions', 'tax'],
    aliases: ['how to save tax', 'tax planning'],
    icon: 'piggy',
    disclaimer: 'tax',
    relatedTools: [
      'income-tax-calculator',
      'ppf-calculator',
      'nps-calculator',
      'hra-tax-exemption-calculator',
    ],
    load: () => t().then((m) => m.TaxSavingCalculator),
  },
]);
