import { defineCategory } from '../define';

const b = () => import('./tools');

export const businessTools = defineCategory('business', [
  {
    slug: 'profit-margin-calculator',
    name: 'Profit Margin Calculator',
    shortDescription: 'Calculate profit, profit margin and markup from cost and selling price.',
    keywords: ['profit margin', 'margin', 'profit', 'cost price', 'selling price', 'business'],
    aliases: ['margin calculator', 'profit percentage', 'profit calculator'],
    icon: 'trending',
    isPopular: true,
    relatedTools: [
      'gross-margin-calculator',
      'net-margin-calculator',
      'markup-calculator',
      'pricing-calculator',
      'discount-calculator',
    ],
    load: () => b().then((m) => m.ProfitMarginCalculator),
  },
  {
    slug: 'gross-margin-calculator',
    name: 'Gross Margin Calculator',
    shortDescription:
      'Calculate gross profit and gross margin from revenue and cost of goods sold.',
    keywords: ['gross margin', 'gross profit', 'cogs', 'revenue', 'margin'],
    aliases: ['gross profit margin'],
    icon: 'pie',
    relatedTools: ['profit-margin-calculator', 'net-margin-calculator', 'markup-calculator'],
    load: () => b().then((m) => m.GrossMarginCalculator),
  },
  {
    slug: 'net-margin-calculator',
    name: 'Net Margin Calculator',
    shortDescription: 'Calculate net profit margin along with gross and operating margins.',
    keywords: ['net margin', 'net profit', 'operating margin', 'ebit', 'profit and loss', 'margin'],
    aliases: ['net profit margin', 'bottom line'],
    icon: 'pie',
    relatedTools: ['gross-margin-calculator', 'profit-margin-calculator', 'break-even-calculator'],
    load: () => b().then((m) => m.NetMarginCalculator),
  },
  {
    slug: 'markup-calculator',
    name: 'Markup Calculator',
    shortDescription:
      'Find the selling price from cost and markup, or the markup percentage from both prices.',
    keywords: ['markup', 'mark up', 'selling price', 'cost plus', 'retail price'],
    aliases: ['markup percentage', 'cost plus pricing'],
    icon: 'tag',
    relatedTools: ['profit-margin-calculator', 'pricing-calculator', 'discount-calculator'],
    load: () => b().then((m) => m.MarkupCalculator),
  },
  {
    slug: 'discount-calculator',
    name: 'Discount Calculator',
    shortDescription:
      'Calculate the final price and savings after a discount, including stacked offers.',
    keywords: ['discount', 'sale', 'offer', 'percent off', 'savings', 'price after discount'],
    aliases: ['sale price', 'percent off calculator', 'discount percentage', 'flat off'],
    icon: 'tag',
    alsoIn: ['everyday'],
    isPopular: true,
    shareSubject: 'discount',
    relatedTools: [
      'percentage-decrease-calculator',
      'markup-calculator',
      'gst-calculator',
      'tip-calculator',
    ],
    load: () => b().then((m) => m.DiscountCalculator),
  },
  {
    slug: 'break-even-calculator',
    name: 'Break-even Calculator',
    shortDescription:
      'Find how many units you must sell to cover fixed costs or hit a profit target.',
    keywords: [
      'break even',
      'break-even point',
      'bep',
      'contribution margin',
      'fixed cost',
      'business',
    ],
    aliases: ['breakeven', 'break even analysis'],
    icon: 'scale',
    relatedTools: [
      'cost-calculator',
      'pricing-calculator',
      'profit-margin-calculator',
      'net-margin-calculator',
    ],
    load: () => b().then((m) => m.BreakEvenCalculator),
  },
  {
    slug: 'roi-calculator',
    name: 'ROI Calculator',
    shortDescription: 'Calculate return on investment and annualised ROI.',
    keywords: ['roi', 'return on investment', 'investment return', 'profit', 'business'],
    aliases: ['return calculator'],
    icon: 'lineChart',
    relatedTools: ['investment-return-calculator', 'cagr-calculator', 'roas-calculator'],
    load: () => b().then((m) => m.RoiCalculator),
  },
  {
    slug: 'roas-calculator',
    name: 'ROAS Calculator',
    shortDescription: 'Calculate return on ad spend and the break-even ROAS for your margin.',
    keywords: ['roas', 'return on ad spend', 'ads', 'marketing', 'facebook ads', 'google ads'],
    aliases: ['ad spend return', 'ads roi'],
    icon: 'target',
    relatedTools: ['roi-calculator', 'profit-margin-calculator', 'revenue-calculator'],
    load: () => b().then((m) => m.RoasCalculator),
  },
  {
    slug: 'revenue-calculator',
    name: 'Revenue Calculator',
    shortDescription: 'Project monthly and total revenue from price, volume and growth.',
    keywords: ['revenue', 'sales', 'turnover', 'revenue projection', 'forecast', 'business'],
    aliases: ['sales forecast', 'revenue forecast'],
    icon: 'chart',
    relatedTools: ['cost-calculator', 'break-even-calculator', 'roas-calculator'],
    load: () => b().then((m) => m.RevenueCalculator),
  },
  {
    slug: 'cost-calculator',
    name: 'Cost Calculator',
    shortDescription: 'Calculate total and per-unit production cost from fixed and variable costs.',
    keywords: [
      'cost',
      'production cost',
      'cost per unit',
      'fixed cost',
      'variable cost',
      'business',
    ],
    aliases: ['unit cost', 'manufacturing cost'],
    icon: 'coins',
    relatedTools: ['break-even-calculator', 'pricing-calculator', 'revenue-calculator'],
    load: () => b().then((m) => m.CostCalculator),
  },
  {
    slug: 'pricing-calculator',
    name: 'Pricing Calculator',
    shortDescription:
      'Set a selling price that covers cost, platform fees, GST and your target margin.',
    keywords: [
      'pricing',
      'selling price',
      'price',
      'margin',
      'marketplace fees',
      'gst',
      'business',
    ],
    aliases: ['price calculator', 'product pricing', 'mrp calculator'],
    icon: 'tag',
    relatedTools: [
      'markup-calculator',
      'profit-margin-calculator',
      'gst-calculator',
      'break-even-calculator',
    ],
    load: () => b().then((m) => m.PricingCalculator),
  },
  {
    slug: 'business-loan-calculator',
    name: 'Business Loan Calculator',
    shortDescription:
      'Calculate business loan EMI, interest and the true annual cost including fees.',
    keywords: ['business loan', 'msme loan', 'emi', 'apr', 'working capital', 'loan'],
    aliases: ['msme loan emi', 'sme loan'],
    icon: 'building',
    alsoIn: ['finance'],
    disclaimer: 'finance',
    relatedTools: ['emi-calculator', 'loan-eligibility-calculator', 'break-even-calculator'],
    load: () => b().then((m) => m.BusinessLoanCalculator),
  },
  {
    slug: 'gst-invoice-calculator',
    name: 'GST Invoice Calculator',
    shortDescription:
      'Build a GST invoice with multiple items and rates, tax summary and amount in words.',
    keywords: ['gst invoice', 'invoice', 'bill', 'tax invoice', 'gst bill', 'cgst', 'sgst'],
    aliases: ['invoice generator', 'gst bill maker', 'billing calculator'],
    icon: 'receipt',
    alsoIn: ['tax'],
    disclaimer: 'tax',
    localOnly: true,
    relatedTools: ['gst-calculator', 'gst-split-calculator', 'tds-calculator'],
    load: () => import('./GstInvoice').then((m) => m.default),
  },
  {
    slug: 'commission-calculator',
    name: 'Commission Calculator',
    shortDescription: 'Calculate flat or tiered sales commission and total earnings.',
    keywords: ['commission', 'sales commission', 'brokerage', 'incentive', 'agent'],
    aliases: ['broker commission', 'sales incentive'],
    icon: 'percent',
    relatedTools: ['tds-calculator', 'percentage-calculator', 'bonus-calculator'],
    load: () => b().then((m) => m.CommissionCalculator),
  },
  {
    slug: 'percentage-increase-calculator',
    name: 'Percentage Increase Calculator',
    shortDescription:
      'Find the percentage increase between two numbers or increase a number by a percentage.',
    keywords: ['percentage increase', 'percent increase', 'growth', 'increase', 'percentage'],
    aliases: ['percent change', 'increase by percent', 'growth percentage'],
    icon: 'trending',
    alsoIn: ['math'],
    relatedTools: [
      'percentage-decrease-calculator',
      'percentage-calculator',
      'percentage-difference-calculator',
      'salary-hike-calculator',
    ],
    load: () => b().then((m) => m.PercentageIncreaseCalculator),
  },
  {
    slug: 'percentage-decrease-calculator',
    name: 'Percentage Decrease Calculator',
    shortDescription:
      'Find the percentage decrease between two numbers or reduce a number by a percentage.',
    keywords: ['percentage decrease', 'percent decrease', 'reduction', 'decline', 'percentage'],
    aliases: ['percent drop', 'decrease by percent'],
    icon: 'trending',
    alsoIn: ['math'],
    relatedTools: [
      'percentage-increase-calculator',
      'discount-calculator',
      'percentage-calculator',
    ],
    load: () => b().then((m) => m.PercentageDecreaseCalculator),
  },
]);
