import { defineCategory } from '../define';

const m = () => import('./tools');

export const mathTools = defineCategory('math', [
  {
    slug: 'percentage-calculator',
    name: 'Percentage Calculator',
    shortDescription:
      'Find X% of Y, what percent X is of Y, the whole from a part, or percentage change.',
    keywords: ['percentage', 'percent', '%', 'percent of', 'what percent', 'math'],
    aliases: ['percentage formula', 'percent calculator', 'calculate percentage'],
    icon: 'percent',
    alsoIn: ['education'],
    isPopular: true,
    isFeatured: true,
    relatedTools: [
      'percentage-increase-calculator',
      'percentage-decrease-calculator',
      'percentage-difference-calculator',
      'marks-percentage-calculator',
      'discount-calculator',
    ],
    load: () => m().then((x) => x.PercentageCalculator),
  },
  {
    slug: 'percentage-difference-calculator',
    name: 'Percentage Difference Calculator',
    shortDescription:
      'Calculate the percentage difference between two values relative to their average.',
    keywords: [
      'percentage difference',
      'percent difference',
      'compare numbers',
      'difference',
      'percentage',
    ],
    aliases: ['relative difference'],
    icon: 'percent',
    relatedTools: [
      'percentage-calculator',
      'percentage-increase-calculator',
      'percentage-decrease-calculator',
    ],
    load: () => m().then((x) => x.PercentageDifferenceCalculator),
  },
  {
    slug: 'fraction-calculator',
    name: 'Fraction Calculator',
    shortDescription:
      'Add, subtract, multiply and divide fractions and mixed numbers with simplified answers.',
    keywords: [
      'fraction',
      'fractions',
      'mixed number',
      'simplify fraction',
      'numerator',
      'denominator',
    ],
    aliases: ['add fractions', 'fraction to decimal'],
    icon: 'divide',
    relatedTools: ['ratio-calculator', 'percentage-calculator', 'gcd-calculator', 'lcm-calculator'],
    load: () => m().then((x) => x.FractionCalculator),
  },
  {
    slug: 'ratio-calculator',
    name: 'Ratio Calculator',
    shortDescription: 'Simplify ratios and divide a total in a given ratio.',
    keywords: ['ratio', 'simplify ratio', 'share in ratio', 'proportion', 'a:b'],
    aliases: ['ratio simplifier', 'divide in ratio'],
    icon: 'scale',
    relatedTools: ['proportion-calculator', 'fraction-calculator', 'percentage-calculator'],
    load: () => m().then((x) => x.RatioCalculator),
  },
  {
    slug: 'proportion-calculator',
    name: 'Proportion Calculator',
    shortDescription: 'Solve A/B = C/D for the missing value using cross-multiplication.',
    keywords: ['proportion', 'cross multiplication', 'rule of three', 'unitary method', 'ratio'],
    aliases: ['solve for x', 'rule of 3'],
    icon: 'scale',
    relatedTools: ['ratio-calculator', 'fraction-calculator', 'percentage-calculator'],
    load: () => m().then((x) => x.ProportionCalculator),
  },
  {
    slug: 'average-calculator',
    name: 'Average Calculator',
    shortDescription:
      'Calculate mean, median, mode, range and standard deviation of a list of numbers.',
    keywords: ['average', 'mean', 'median', 'mode', 'standard deviation', 'statistics'],
    aliases: ['mean median mode', 'find average'],
    icon: 'sigma',
    relatedTools: [
      'weighted-average-calculator',
      'average-marks-calculator',
      'percentage-calculator',
    ],
    load: () => m().then((x) => x.AverageCalculator),
  },
  {
    slug: 'weighted-average-calculator',
    name: 'Weighted Average Calculator',
    shortDescription: 'Calculate a weighted average from values and their weights.',
    keywords: ['weighted average', 'weighted mean', 'weights', 'average', 'credits'],
    aliases: ['weighted mean calculator'],
    icon: 'sigma',
    relatedTools: ['average-calculator', 'gpa-calculator', 'cgpa-calculator'],
    load: () => m().then((x) => x.WeightedAverageCalculator),
  },
  {
    slug: 'scientific-calculator',
    name: 'Scientific Calculator',
    shortDescription:
      'Online scientific calculator with trigonometry, logarithms, powers, roots and factorials.',
    keywords: ['scientific calculator', 'calculator', 'trigonometry', 'sin', 'cos', 'log', 'math'],
    aliases: ['online calculator', 'casio calculator', 'basic calculator'],
    icon: 'calculator',
    isPopular: true,
    localOnly: true,
    relatedTools: [
      'exponent-calculator',
      'square-root-calculator',
      'factorial-calculator',
      'percentage-calculator',
    ],
    load: () => import('./ScientificCalculator').then((x) => x.default),
  },
  {
    slug: 'exponent-calculator',
    name: 'Exponent Calculator',
    shortDescription:
      'Raise a number to any power, with exact results for large whole-number powers.',
    keywords: ['exponent', 'power', 'raise to power', 'indices', 'x^y'],
    aliases: ['power calculator', 'x to the power y'],
    icon: 'func',
    relatedTools: ['square-root-calculator', 'cube-root-calculator', 'scientific-calculator'],
    load: () => m().then((x) => x.ExponentCalculator),
  },
  {
    slug: 'square-root-calculator',
    name: 'Square Root Calculator',
    shortDescription: 'Find the square root of a number and its simplified radical form.',
    keywords: ['square root', 'sqrt', 'root', 'radical', 'perfect square'],
    aliases: ['√ calculator', 'root of number'],
    icon: 'radical',
    relatedTools: ['cube-root-calculator', 'exponent-calculator', 'scientific-calculator'],
    load: () => m().then((x) => x.SquareRootCalculator),
  },
  {
    slug: 'cube-root-calculator',
    name: 'Cube Root Calculator',
    shortDescription:
      'Find the cube root of any number, including negatives, with simplified form.',
    keywords: ['cube root', 'cbrt', 'root', 'perfect cube', 'radical'],
    aliases: ['∛ calculator'],
    icon: 'radical',
    relatedTools: ['square-root-calculator', 'exponent-calculator', 'scientific-calculator'],
    load: () => m().then((x) => x.CubeRootCalculator),
  },
  {
    slug: 'gcd-calculator',
    name: 'GCD Calculator',
    shortDescription: 'Find the greatest common divisor (HCF) of two or more numbers.',
    keywords: ['gcd', 'hcf', 'greatest common divisor', 'highest common factor', 'gcf'],
    aliases: ['hcf calculator', 'gcf calculator'],
    icon: 'hash',
    relatedTools: ['lcm-calculator', 'fraction-calculator', 'prime-number-checker'],
    load: () => m().then((x) => x.GcdCalculator),
  },
  {
    slug: 'lcm-calculator',
    name: 'LCM Calculator',
    shortDescription: 'Find the least common multiple of two or more numbers.',
    keywords: ['lcm', 'least common multiple', 'lowest common multiple', 'multiples'],
    aliases: ['lowest common multiple calculator'],
    icon: 'hash',
    relatedTools: ['gcd-calculator', 'fraction-calculator', 'prime-number-checker'],
    load: () => m().then((x) => x.LcmCalculator),
  },
  {
    slug: 'prime-number-checker',
    name: 'Prime Number Checker',
    shortDescription: 'Check whether a number is prime and see its prime factorisation.',
    keywords: ['prime number', 'is prime', 'prime check', 'prime factorization', 'composite'],
    aliases: ['prime calculator', 'prime factors'],
    icon: 'hash',
    relatedTools: ['gcd-calculator', 'lcm-calculator', 'factorial-calculator'],
    load: () => m().then((x) => x.PrimeNumberChecker),
  },
  {
    slug: 'random-number-generator',
    name: 'Random Number Generator',
    shortDescription: 'Generate secure random numbers in any range, with or without repeats.',
    keywords: ['random number', 'rng', 'random', 'lottery numbers', 'dice', 'generator'],
    aliases: ['random picker numbers', 'number generator'],
    icon: 'dice',
    localOnly: true,
    relatedTools: ['random-picker', 'password-generator', 'uuid-generator'],
    load: () => m().then((x) => x.RandomNumberGenerator),
  },
  {
    slug: 'factorial-calculator',
    name: 'Factorial Calculator',
    shortDescription: 'Calculate the exact factorial n! of numbers up to 5,000.',
    keywords: ['factorial', 'n!', 'permutation', 'math'],
    aliases: ['n factorial'],
    icon: 'hash',
    relatedTools: ['permutation-calculator', 'combination-calculator', 'scientific-calculator'],
    load: () => m().then((x) => x.FactorialCalculator),
  },
  {
    slug: 'permutation-calculator',
    name: 'Permutation Calculator',
    shortDescription:
      'Calculate nPr — the number of ordered arrangements — with or without repetition.',
    keywords: ['permutation', 'npr', 'arrangements', 'order matters', 'probability'],
    aliases: ['npr calculator'],
    icon: 'shuffle',
    relatedTools: ['combination-calculator', 'factorial-calculator'],
    load: () => m().then((x) => x.PermutationCalculator),
  },
  {
    slug: 'combination-calculator',
    name: 'Combination Calculator',
    shortDescription:
      'Calculate nCr — the number of ways to choose items when order does not matter.',
    keywords: ['combination', 'ncr', 'choose', 'binomial coefficient', 'probability'],
    aliases: ['ncr calculator', 'n choose r'],
    icon: 'shuffle',
    relatedTools: ['permutation-calculator', 'factorial-calculator'],
    load: () => m().then((x) => x.CombinationCalculator),
  },
]);
