import {
  Activity,
  AlarmClock,
  AlignLeft,
  Apple,
  ArrowLeftRight,
  Baby,
  Banknote,
  BarChart3,
  Bed,
  Binary,
  BookOpen,
  Braces,
  Briefcase,
  Building2,
  Calculator,
  CalendarClock,
  CalendarDays,
  Car,
  CaseSensitive,
  Clock,
  Code2,
  Coins,
  Compass,
  Database,
  Dices,
  Divide,
  Droplets,
  Dumbbell,
  Eraser,
  FileCode,
  FileJson,
  FileText,
  Fingerprint,
  Flame,
  Fuel,
  Gauge,
  GitCompare,
  Globe,
  GraduationCap,
  HardDrive,
  Hash,
  HeartPulse,
  Hourglass,
  House,
  IndianRupee,
  KeyRound,
  Landmark,
  Layers,
  LineChart,
  Link,
  ListOrdered,
  Lock,
  Monitor,
  Moon,
  Network,
  Palette,
  Percent,
  PieChart,
  PiggyBank,
  Plug,
  Radical,
  Radio,
  Receipt,
  Regex,
  Replace,
  Ruler,
  Scale,
  Scissors,
  Shuffle,
  Sigma,
  Split,
  Square,
  SquareFunction,
  Tag,
  Target,
  Thermometer,
  Timer,
  TrendingUp,
  Type,
  Users,
  Utensils,
  Wallet,
  Weight,
  Wind,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';

export const ICONS = {
  activity: Activity,
  alarm: AlarmClock,
  align: AlignLeft,
  apple: Apple,
  swap: ArrowLeftRight,
  baby: Baby,
  banknote: Banknote,
  chart: BarChart3,
  bed: Bed,
  binary: Binary,
  book: BookOpen,
  braces: Braces,
  briefcase: Briefcase,
  building: Building2,
  calculator: Calculator,
  calendarClock: CalendarClock,
  calendar: CalendarDays,
  car: Car,
  case: CaseSensitive,
  clock: Clock,
  code: Code2,
  coins: Coins,
  compass: Compass,
  database: Database,
  dice: Dices,
  divide: Divide,
  droplets: Droplets,
  dumbbell: Dumbbell,
  eraser: Eraser,
  fileCode: FileCode,
  json: FileJson,
  file: FileText,
  fingerprint: Fingerprint,
  flame: Flame,
  fuel: Fuel,
  gauge: Gauge,
  compare: GitCompare,
  globe: Globe,
  graduation: GraduationCap,
  storage: HardDrive,
  hash: Hash,
  heart: HeartPulse,
  hourglass: Hourglass,
  home: House,
  rupee: IndianRupee,
  key: KeyRound,
  bank: Landmark,
  layers: Layers,
  lineChart: LineChart,
  link: Link,
  list: ListOrdered,
  lock: Lock,
  monitor: Monitor,
  moon: Moon,
  network: Network,
  palette: Palette,
  percent: Percent,
  pie: PieChart,
  piggy: PiggyBank,
  plug: Plug,
  radical: Radical,
  radio: Radio,
  receipt: Receipt,
  regex: Regex,
  replace: Replace,
  ruler: Ruler,
  scale: Scale,
  scissors: Scissors,
  shuffle: Shuffle,
  sigma: Sigma,
  split: Split,
  square: Square,
  func: SquareFunction,
  tag: Tag,
  target: Target,
  thermometer: Thermometer,
  timer: Timer,
  trending: TrendingUp,
  type: Type,
  users: Users,
  utensils: Utensils,
  wallet: Wallet,
  weight: Weight,
  wind: Wind,
  wrench: Wrench,
  zap: Zap,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export function ToolIcon({ name, className = 'h-5 w-5' }: { name: IconName; className?: string }) {
  const Icon = ICONS[name] ?? Calculator;
  return <Icon className={className} aria-hidden="true" focusable="false" />;
}
