import { defineCategory } from '../define';

const c = () => import('./tools');
const REL = [
  'length-converter',
  'weight-converter',
  'area-converter',
  'temperature-converter',
  'volume-converter',
];
const rel = (self: string, extra: string[] = []) =>
  [...new Set([...extra, ...REL])].filter((s) => s !== self).slice(0, 6);

export const converterTools = defineCategory('converters', [
  {
    slug: 'length-converter',
    name: 'Length Converter',
    shortDescription:
      'Convert between metres, feet, inches, centimetres, kilometres, miles, yards and more.',
    keywords: [
      'length',
      'distance',
      'feet to meter',
      'cm to inch',
      'km to mile',
      'convert length',
      'metre',
    ],
    aliases: ['ft to m', 'inch to cm', 'meter to feet', 'km to miles'],
    icon: 'ruler',
    isPopular: true,
    localOnly: true,
    relatedTools: rel('length-converter', ['height-converter', 'area-converter']),
    load: () => c().then((m) => m.LengthConverter),
  },
  {
    slug: 'weight-converter',
    name: 'Weight Converter',
    shortDescription: 'Convert kg, grams, pounds, ounces, tonnes, quintals, tola and more.',
    keywords: ['weight', 'mass', 'kg', 'kg to lbs', 'pound', 'gram', 'tola', 'convert weight'],
    aliases: ['kg to pounds', 'lbs to kg', 'gram to tola', 'mass converter'],
    icon: 'weight',
    isPopular: true,
    localOnly: true,
    relatedTools: rel('weight-converter', ['bmi-calculator', 'cooking-unit-converter']),
    load: () => c().then((m) => m.WeightConverter),
  },
  {
    slug: 'height-converter',
    name: 'Height Converter',
    shortDescription: 'Convert height between feet and inches and centimetres.',
    keywords: [
      'height',
      'feet inches to cm',
      'cm to feet',
      '5 feet 7 inches in cm',
      'height conversion',
    ],
    aliases: ['ft in to cm', 'cm to ft', 'height in cm'],
    icon: 'ruler',
    localOnly: true,
    relatedTools: ['length-converter', 'bmi-calculator', 'ideal-weight-calculator'],
    load: () => c().then((m) => m.HeightConverter),
  },
  {
    slug: 'temperature-converter',
    name: 'Temperature Converter',
    shortDescription: 'Convert Celsius, Fahrenheit, Kelvin and Rankine.',
    keywords: ['temperature', 'celsius to fahrenheit', 'fahrenheit to celsius', 'kelvin', 'fever'],
    aliases: ['c to f', 'f to c', '°c to °f'],
    icon: 'thermometer',
    isPopular: true,
    localOnly: true,
    relatedTools: rel('temperature-converter', ['cooking-unit-converter']),
    load: () => c().then((m) => m.TemperatureConverter),
  },
  {
    slug: 'area-converter',
    name: 'Area Converter',
    shortDescription:
      'Convert sq ft, sq m, acres, hectares, gaj and Indian land units like bigha, guntha and cent.',
    keywords: [
      'area',
      'land area',
      'square feet',
      'acre',
      'hectare',
      'bigha',
      'guntha',
      'cent',
      'gaj',
      'marla',
    ],
    aliases: ['sq ft to sq m', 'acre to sq ft', 'bigha to acre', 'gaj to sq ft', 'land converter'],
    icon: 'square',
    isPopular: true,
    localOnly: true,
    relatedTools: rel('area-converter', ['length-converter']),
    load: () => c().then((m) => m.AreaConverter),
  },
  {
    slug: 'volume-converter',
    name: 'Volume Converter',
    shortDescription: 'Convert litres, millilitres, gallons, cups, cubic metres and more.',
    keywords: ['volume', 'litre', 'liter', 'gallon', 'ml', 'cubic', 'capacity'],
    aliases: ['litre to gallon', 'ml to cup'],
    icon: 'droplets',
    localOnly: true,
    relatedTools: rel('volume-converter', ['cooking-unit-converter']),
    load: () => c().then((m) => m.VolumeConverter),
  },
  {
    slug: 'speed-converter',
    name: 'Speed Converter',
    shortDescription: 'Convert km/h, mph, m/s, knots and Mach.',
    keywords: ['speed', 'kmph', 'km/h to mph', 'knots', 'velocity'],
    aliases: ['kmph to mph', 'mph to kmph'],
    icon: 'gauge',
    localOnly: true,
    relatedTools: ['length-converter', 'time-converter', 'fuel-economy-converter'],
    load: () => c().then((m) => m.SpeedConverter),
  },
  {
    slug: 'time-converter',
    name: 'Time Converter',
    shortDescription: 'Convert seconds, minutes, hours, days, weeks, months and years.',
    keywords: ['time', 'hours to minutes', 'seconds', 'days', 'time units'],
    aliases: ['minutes to hours', 'seconds to hours'],
    icon: 'timer',
    localOnly: true,
    relatedTools: ['time-duration-calculator', 'speed-converter', 'date-difference-calculator'],
    load: () => c().then((m) => m.TimeConverter),
  },
  {
    slug: 'data-storage-converter',
    name: 'Data Storage Converter',
    shortDescription: 'Convert bits, bytes, KB, MB, GB, TB and binary KiB, MiB, GiB.',
    keywords: ['data', 'storage', 'mb to gb', 'gb to mb', 'bytes', 'kib', 'bandwidth'],
    aliases: ['file size converter', 'gb to tb'],
    icon: 'storage',
    alsoIn: ['developer'],
    localOnly: true,
    relatedTools: ['frequency-converter', 'base64-encoder', 'time-converter'],
    load: () => c().then((m) => m.DataStorageConverter),
  },
  {
    slug: 'energy-converter',
    name: 'Energy Converter',
    shortDescription: 'Convert joules, calories, kilocalories, kWh (units), BTU and more.',
    keywords: ['energy', 'calories', 'kcal to kj', 'kwh', 'joule', 'btu'],
    aliases: ['kcal to kj', 'kwh to joules'],
    icon: 'zap',
    localOnly: true,
    relatedTools: ['power-converter', 'electricity-cost-calculator', 'calorie-calculator'],
    load: () => c().then((m) => m.EnergyConverter),
  },
  {
    slug: 'power-converter',
    name: 'Power Converter',
    shortDescription: 'Convert watts, kilowatts, horsepower, PS, BTU/h and AC tons.',
    keywords: ['power', 'watt', 'horsepower', 'hp to kw', 'ac ton', 'btu'],
    aliases: ['hp to kw', 'ton to watt'],
    icon: 'plug',
    localOnly: true,
    relatedTools: ['energy-converter', 'electricity-cost-calculator'],
    load: () => c().then((m) => m.PowerConverter),
  },
  {
    slug: 'pressure-converter',
    name: 'Pressure Converter',
    shortDescription: 'Convert psi, bar, kPa, atm, mmHg and kgf/cm² — handy for tyres.',
    keywords: ['pressure', 'psi to bar', 'tyre pressure', 'kpa', 'atm', 'mmhg'],
    aliases: ['psi to bar', 'bar to psi'],
    icon: 'gauge',
    localOnly: true,
    relatedTools: ['temperature-converter', 'volume-converter'],
    load: () => c().then((m) => m.PressureConverter),
  },
  {
    slug: 'fuel-economy-converter',
    name: 'Fuel Economy Converter',
    shortDescription: 'Convert km/L, L/100 km and miles per gallon (US and UK).',
    keywords: ['fuel economy', 'mileage', 'kmpl', 'mpg', 'l/100km'],
    aliases: ['mpg to kmpl', 'kmpl to l/100km'],
    icon: 'fuel',
    localOnly: true,
    relatedTools: ['fuel-mileage-calculator', 'fuel-cost-calculator', 'speed-converter'],
    load: () => c().then((m) => m.FuelEconomyConverter),
  },
  {
    slug: 'frequency-converter',
    name: 'Frequency Converter',
    shortDescription: 'Convert Hz, kHz, MHz, GHz, RPM and radians per second.',
    keywords: ['frequency', 'hertz', 'mhz', 'ghz', 'rpm'],
    aliases: ['hz to rpm'],
    icon: 'radio',
    localOnly: true,
    relatedTools: ['angle-converter', 'data-storage-converter', 'time-converter'],
    load: () => c().then((m) => m.FrequencyConverter),
  },
  {
    slug: 'angle-converter',
    name: 'Angle Converter',
    shortDescription: 'Convert degrees, radians, gradians, arcminutes and arcseconds.',
    keywords: ['angle', 'degrees to radians', 'radians', 'gradian', 'arcminute'],
    aliases: ['deg to rad', 'rad to deg'],
    icon: 'compass',
    localOnly: true,
    relatedTools: ['scientific-calculator', 'frequency-converter'],
    load: () => c().then((m) => m.AngleConverter),
  },
]);
