import { defineCategory } from '../define';

const s = () => import('./tools');

export const salaryTools = defineCategory('salary', [
  {
    slug: 'ctc-to-in-hand-salary-calculator',
    name: 'CTC to In-Hand Salary Calculator',
    shortDescription:
      'Convert your CTC into monthly take-home salary after PF, professional tax and income tax.',
    keywords: [
      'ctc',
      'in hand',
      'take home',
      'salary',
      'net salary',
      'ctc to in hand',
      'monthly salary',
    ],
    aliases: [
      'take home salary',
      'in hand salary from ctc',
      'salary calculator',
      'net pay',
      'ctc calculator',
    ],
    icon: 'wallet',
    isPopular: true,
    isFeatured: true,
    disclaimer: 'tax',
    shareSubject: 'in-hand salary',
    relatedTools: [
      'salary-breakup-calculator',
      'income-tax-calculator',
      'salary-hike-calculator',
      'hra-calculator',
      'pf-calculator',
      'offer-comparison-calculator',
    ],
    load: () => s().then((m) => m.CtcToInHandCalculator),
  },
  {
    slug: 'in-hand-salary-calculator',
    name: 'In-Hand Salary Calculator',
    shortDescription:
      'Calculate net monthly salary from your gross salary after PF, ESI, PT and TDS.',
    keywords: ['in hand salary', 'net salary', 'take home', 'gross to net', 'salary', 'tds'],
    aliases: ['gross to net salary', 'net pay calculator', 'take home pay'],
    icon: 'wallet',
    disclaimer: 'tax',
    shareSubject: 'in-hand salary',
    relatedTools: [
      'ctc-to-in-hand-salary-calculator',
      'income-tax-calculator',
      'employee-contribution-calculator',
      'salary-breakup-calculator',
    ],
    load: () => s().then((m) => m.InHandSalaryCalculator),
  },
  {
    slug: 'salary-hike-calculator',
    name: 'Salary Hike Calculator',
    shortDescription:
      'Find your new salary after a hike, or the hike percentage between two salaries.',
    keywords: ['salary hike', 'hike percentage', 'appraisal', 'raise', 'salary', 'job switch'],
    aliases: ['hike calculator', 'pay raise', 'appraisal calculator', 'salary increase percentage'],
    icon: 'trending',
    isPopular: true,
    shareSubject: 'salary hike',
    relatedTools: [
      'salary-increment-calculator',
      'ctc-to-in-hand-salary-calculator',
      'offer-comparison-calculator',
      'percentage-increase-calculator',
    ],
    load: () => s().then((m) => m.SalaryHikeCalculator),
  },
  {
    slug: 'salary-increment-calculator',
    name: 'Salary Increment Calculator',
    shortDescription:
      'Project your salary over the years with a yearly increment and see real growth after inflation.',
    keywords: [
      'increment',
      'salary increment',
      'annual increment',
      'salary growth',
      'salary',
      'projection',
    ],
    aliases: ['yearly increment', 'salary projection'],
    icon: 'lineChart',
    relatedTools: [
      'salary-hike-calculator',
      'inflation-calculator',
      'ctc-to-in-hand-salary-calculator',
    ],
    load: () => s().then((m) => m.SalaryIncrementCalculator),
  },
  {
    slug: 'salary-comparison-calculator',
    name: 'Salary Comparison Calculator',
    shortDescription:
      'Compare two salaries paid hourly, daily, weekly, monthly or yearly on the same basis.',
    keywords: [
      'salary comparison',
      'compare salary',
      'salary',
      'pay comparison',
      'hourly vs monthly',
    ],
    aliases: ['compare two salaries'],
    icon: 'compare',
    relatedTools: [
      'offer-comparison-calculator',
      'annual-salary-calculator',
      'hourly-salary-calculator',
      'salary-hike-calculator',
    ],
    load: () => s().then((m) => m.SalaryComparisonCalculator),
  },
  {
    slug: 'monthly-salary-calculator',
    name: 'Monthly Salary Calculator',
    shortDescription: 'Convert annual, weekly, daily or hourly pay into a monthly salary.',
    keywords: [
      'monthly salary',
      'annual to monthly',
      'salary per month',
      'salary',
      'lpa to monthly',
    ],
    aliases: ['lpa to monthly', 'yearly to monthly salary'],
    icon: 'calendar',
    relatedTools: [
      'annual-salary-calculator',
      'daily-salary-calculator',
      'hourly-salary-calculator',
      'ctc-to-in-hand-salary-calculator',
    ],
    load: () => s().then((m) => m.MonthlySalaryCalculator),
  },
  {
    slug: 'annual-salary-calculator',
    name: 'Annual Salary Calculator',
    shortDescription: 'Convert monthly, weekly, daily or hourly pay into annual salary (LPA).',
    keywords: ['annual salary', 'yearly salary', 'lpa', 'monthly to annual', 'salary', 'package'],
    aliases: ['monthly to lpa', 'salary per year'],
    icon: 'calendar',
    relatedTools: [
      'monthly-salary-calculator',
      'hourly-salary-calculator',
      'salary-comparison-calculator',
    ],
    load: () => s().then((m) => m.AnnualSalaryCalculator),
  },
  {
    slug: 'daily-salary-calculator',
    name: 'Daily Salary Calculator',
    shortDescription: 'Work out per-day salary and loss-of-pay deductions for unpaid leave.',
    keywords: ['daily salary', 'per day salary', 'lop', 'loss of pay', 'daily wage', 'salary'],
    aliases: ['per day salary', 'lop calculator', 'salary deduction for leave'],
    icon: 'calendar',
    relatedTools: [
      'monthly-salary-calculator',
      'hourly-salary-calculator',
      'leave-encashment-calculator',
    ],
    load: () => s().then((m) => m.DailySalaryCalculator),
  },
  {
    slug: 'hourly-salary-calculator',
    name: 'Hourly Salary Calculator',
    shortDescription: 'Convert your monthly or annual salary into an hourly rate.',
    keywords: ['hourly salary', 'per hour', 'hourly rate', 'hourly wage', 'salary'],
    aliases: ['salary per hour', 'hourly pay'],
    icon: 'clock',
    relatedTools: [
      'freelance-hourly-rate-calculator',
      'annual-salary-calculator',
      'daily-salary-calculator',
    ],
    load: () => s().then((m) => m.HourlySalaryCalculator),
  },
  {
    slug: 'freelance-hourly-rate-calculator',
    name: 'Freelance Hourly Rate Calculator',
    shortDescription:
      'Set a freelance hourly and day rate that covers your income goal, expenses, taxes and time off.',
    keywords: ['freelance', 'hourly rate', 'consultant rate', 'day rate', 'freelancer', 'pricing'],
    aliases: ['freelancer rate', 'consulting fee'],
    icon: 'briefcase',
    relatedTools: [
      'hourly-salary-calculator',
      'pricing-calculator',
      'gst-calculator',
      'income-tax-calculator',
    ],
    load: () => s().then((m) => m.FreelanceHourlyRateCalculator),
  },
  {
    slug: 'gratuity-calculator',
    name: 'Gratuity Calculator',
    shortDescription:
      'Calculate gratuity under the Payment of Gratuity Act and its tax-exempt amount.',
    keywords: [
      'gratuity',
      'salary',
      'resignation',
      'retirement',
      'payment of gratuity act',
      '15/26',
    ],
    aliases: ['gratuity amount', 'gratuity formula'],
    icon: 'coins',
    isPopular: true,
    disclaimer: 'finance',
    shareSubject: 'gratuity',
    relatedTools: [
      'leave-encashment-calculator',
      'epf-calculator',
      'notice-period-calculator',
      'experience-calculator',
    ],
    load: () => s().then((m) => m.GratuityCalculator),
  },
  {
    slug: 'epf-calculator',
    name: 'EPF Calculator',
    shortDescription:
      'Project your Employees’ Provident Fund corpus at retirement with salary growth.',
    keywords: ['epf', 'provident fund', 'pf balance', 'retirement', 'epfo', 'salary', 'vpf'],
    aliases: ['epf corpus', 'pf maturity', 'epfo calculator'],
    icon: 'piggy',
    isPopular: true,
    disclaimer: 'finance',
    relatedTools: [
      'pf-calculator',
      'ppf-calculator',
      'retirement-calculator',
      'employer-contribution-calculator',
    ],
    load: () => s().then((m) => m.EpfCalculator),
  },
  {
    slug: 'pf-calculator',
    name: 'PF Calculator',
    shortDescription: 'See the monthly PF split between employee, employer EPF and EPS pension.',
    keywords: ['pf', 'provident fund', 'pf contribution', 'eps', 'salary', 'pf deduction'],
    aliases: ['pf deduction', 'pf contribution calculator'],
    icon: 'piggy',
    relatedTools: [
      'epf-calculator',
      'employee-contribution-calculator',
      'employer-contribution-calculator',
      'ctc-to-in-hand-salary-calculator',
    ],
    load: () => s().then((m) => m.PfCalculator),
  },
  {
    slug: 'employee-contribution-calculator',
    name: 'Employee Contribution Calculator',
    shortDescription: 'Calculate employee PF, VPF, ESI and professional tax deducted from salary.',
    keywords: ['employee contribution', 'pf', 'esi', 'professional tax', 'salary deductions'],
    aliases: ['salary deductions calculator', 'esi calculator'],
    icon: 'users',
    relatedTools: [
      'employer-contribution-calculator',
      'pf-calculator',
      'in-hand-salary-calculator',
    ],
    load: () => s().then((m) => m.EmployeeContributionCalculator),
  },
  {
    slug: 'employer-contribution-calculator',
    name: 'Employer Contribution Calculator',
    shortDescription:
      'Calculate the employer’s PF, EPS, EDLI, ESI and gratuity cost on top of gross salary.',
    keywords: ['employer contribution', 'employer pf', 'esi', 'edli', 'cost to company', 'payroll'],
    aliases: ['employer cost', 'cost to company calculator'],
    icon: 'building',
    relatedTools: [
      'employee-contribution-calculator',
      'pf-calculator',
      'salary-breakup-calculator',
    ],
    load: () => s().then((m) => m.EmployerContributionCalculator),
  },
  {
    slug: 'hra-calculator',
    name: 'HRA Calculator',
    shortDescription: 'Calculate exempt and taxable HRA from basic, HRA received and rent paid.',
    keywords: ['hra', 'house rent allowance', 'rent', 'hra exemption', 'salary', 'tax'],
    aliases: ['house rent allowance calculator', 'hra exemption'],
    icon: 'home',
    isPopular: true,
    disclaimer: 'tax',
    relatedTools: [
      'hra-tax-exemption-calculator',
      'income-tax-calculator',
      'ctc-to-in-hand-salary-calculator',
      'tax-saving-calculator',
    ],
    load: () => s().then((m) => m.HraCalculator),
  },
  {
    slug: 'bonus-calculator',
    name: 'Bonus Calculator',
    shortDescription:
      'Calculate statutory bonus under the Payment of Bonus Act or a performance bonus after tax.',
    keywords: [
      'bonus',
      'statutory bonus',
      'performance bonus',
      'diwali bonus',
      'salary',
      'bonus act',
    ],
    aliases: ['bonus act calculator', 'annual bonus'],
    icon: 'banknote',
    relatedTools: [
      'ctc-to-in-hand-salary-calculator',
      'salary-hike-calculator',
      'income-tax-calculator',
    ],
    load: () => s().then((m) => m.BonusCalculator),
  },
  {
    slug: 'leave-encashment-calculator',
    name: 'Leave Encashment Calculator',
    shortDescription:
      'Calculate leave encashment and the tax-exempt amount on retirement or resignation.',
    keywords: [
      'leave encashment',
      'earned leave',
      'privilege leave',
      'salary',
      'retirement',
      'tax exemption',
    ],
    aliases: ['el encashment', 'leave salary'],
    icon: 'calendarClock',
    disclaimer: 'tax',
    relatedTools: ['gratuity-calculator', 'notice-period-calculator', 'daily-salary-calculator'],
    load: () => s().then((m) => m.LeaveEncashmentCalculator),
  },
  {
    slug: 'notice-period-calculator',
    name: 'Notice Period Calculator',
    shortDescription:
      'Find your last working day and notice buyout amount from your resignation date.',
    keywords: ['notice period', 'last working day', 'resignation', 'notice buyout', 'lwd'],
    aliases: ['last working day calculator', 'notice buyout'],
    icon: 'calendar',
    relatedTools: [
      'experience-calculator',
      'gratuity-calculator',
      'leave-encashment-calculator',
      'add-days-calculator',
    ],
    load: () => s().then((m) => m.NoticePeriodCalculator),
  },
  {
    slug: 'experience-calculator',
    name: 'Experience Calculator',
    shortDescription:
      'Add up total work experience across jobs, counting overlapping periods once.',
    keywords: [
      'experience',
      'work experience',
      'total experience',
      'years of experience',
      'career',
    ],
    aliases: ['total work experience', 'experience in years'],
    icon: 'briefcase',
    relatedTools: ['notice-period-calculator', 'date-difference-calculator', 'gratuity-calculator'],
    load: () => s().then((m) => m.ExperienceCalculator),
  },
  {
    slug: 'offer-comparison-calculator',
    name: 'Offer Comparison Calculator',
    shortDescription: 'Compare two job offers by fixed monthly take-home and first-year cash.',
    keywords: ['offer comparison', 'job offer', 'compare offers', 'ctc', 'salary', 'switch'],
    aliases: ['compare job offers', 'which offer is better'],
    icon: 'compare',
    disclaimer: 'tax',
    relatedTools: [
      'ctc-to-in-hand-salary-calculator',
      'salary-hike-calculator',
      'salary-comparison-calculator',
    ],
    load: () => s().then((m) => m.OfferComparisonCalculator),
  },
  {
    slug: 'salary-breakup-calculator',
    name: 'Salary Breakup Calculator',
    shortDescription:
      'Split CTC into basic, HRA, special allowance, PF and gratuity — monthly and annual.',
    keywords: [
      'salary breakup',
      'salary structure',
      'ctc breakup',
      'basic',
      'hra',
      'special allowance',
      'salary',
    ],
    aliases: ['salary structure calculator', 'ctc breakdown'],
    icon: 'pie',
    relatedTools: [
      'ctc-to-in-hand-salary-calculator',
      'hra-calculator',
      'employer-contribution-calculator',
    ],
    load: () => s().then((m) => m.SalaryBreakupCalculator),
  },
]);
