import { ALL_TOOLS, TOOL_BY_SLUG, toolsInCategory } from './registry';
import type { CategoryId } from '@/types/tool';

/**
 * The product specification's numbered catalogue (212 entries) mapped to registered tools.
 * Entries that the spec lists in more than one category (e.g. Age Calculator in Date & Time,
 * Education and Everyday) intentionally resolve to ONE tool that is cross-listed via `alsoIn`.
 */
const CATALOGUE: [number, CategoryId, string][] = [
  [1, 'finance', 'emi-calculator'],
  [2, 'finance', 'home-loan-emi-calculator'],
  [3, 'finance', 'personal-loan-emi-calculator'],
  [4, 'finance', 'car-loan-emi-calculator'],
  [5, 'finance', 'education-loan-emi-calculator'],
  [6, 'finance', 'loan-eligibility-calculator'],
  [7, 'finance', 'loan-tenure-calculator'],
  [8, 'finance', 'loan-prepayment-calculator'],
  [9, 'finance', 'loan-amortization-calculator'],
  [10, 'finance', 'sip-calculator'],
  [11, 'finance', 'sip-returns-calculator'],
  [12, 'finance', 'lump-sum-calculator'],
  [13, 'finance', 'swp-calculator'],
  [14, 'finance', 'stp-calculator'],
  [15, 'finance', 'fd-calculator'],
  [16, 'finance', 'rd-calculator'],
  [17, 'finance', 'ppf-calculator'],
  [18, 'finance', 'nps-calculator'],
  [19, 'finance', 'cagr-calculator'],
  [20, 'finance', 'simple-interest-calculator'],
  [21, 'finance', 'compound-interest-calculator'],
  [22, 'finance', 'inflation-calculator'],
  [23, 'finance', 'retirement-calculator'],
  [24, 'finance', 'retirement-corpus-calculator'],
  [25, 'finance', 'net-worth-calculator'],
  [26, 'finance', 'investment-return-calculator'],
  [27, 'finance', 'future-value-calculator'],
  [28, 'finance', 'present-value-calculator'],
  [29, 'finance', 'rule-of-72-calculator'],
  [30, 'salary', 'ctc-to-in-hand-salary-calculator'],
  [31, 'salary', 'in-hand-salary-calculator'],
  [32, 'salary', 'salary-hike-calculator'],
  [33, 'salary', 'salary-increment-calculator'],
  [34, 'salary', 'salary-comparison-calculator'],
  [35, 'salary', 'monthly-salary-calculator'],
  [36, 'salary', 'annual-salary-calculator'],
  [37, 'salary', 'daily-salary-calculator'],
  [38, 'salary', 'hourly-salary-calculator'],
  [39, 'salary', 'freelance-hourly-rate-calculator'],
  [40, 'salary', 'gratuity-calculator'],
  [41, 'salary', 'epf-calculator'],
  [42, 'salary', 'pf-calculator'],
  [43, 'salary', 'employee-contribution-calculator'],
  [44, 'salary', 'employer-contribution-calculator'],
  [45, 'salary', 'hra-calculator'],
  [46, 'salary', 'bonus-calculator'],
  [47, 'salary', 'leave-encashment-calculator'],
  [48, 'salary', 'notice-period-calculator'],
  [49, 'salary', 'experience-calculator'],
  [50, 'salary', 'offer-comparison-calculator'],
  [51, 'salary', 'salary-breakup-calculator'],
  [52, 'tax', 'gst-calculator'],
  [53, 'tax', 'gst-inclusive-calculator'],
  [54, 'tax', 'gst-exclusive-calculator'],
  [55, 'tax', 'gst-reverse-calculator'],
  [56, 'tax', 'gst-split-calculator'],
  [57, 'tax', 'gst-amount-calculator'],
  [58, 'tax', 'income-tax-calculator'],
  [59, 'tax', 'hra-tax-exemption-calculator'],
  [60, 'tax', 'tds-calculator'],
  [61, 'tax', 'capital-gains-calculator'],
  [62, 'tax', 'tax-saving-calculator'],
  [63, 'business', 'profit-margin-calculator'],
  [64, 'business', 'gross-margin-calculator'],
  [65, 'business', 'net-margin-calculator'],
  [66, 'business', 'markup-calculator'],
  [67, 'business', 'discount-calculator'],
  [68, 'business', 'break-even-calculator'],
  [69, 'business', 'roi-calculator'],
  [70, 'business', 'roas-calculator'],
  [71, 'business', 'revenue-calculator'],
  [72, 'business', 'cost-calculator'],
  [73, 'business', 'pricing-calculator'],
  [74, 'business', 'business-loan-calculator'],
  [75, 'business', 'gst-invoice-calculator'],
  [76, 'business', 'commission-calculator'],
  [77, 'business', 'percentage-increase-calculator'],
  [78, 'business', 'percentage-decrease-calculator'],
  [79, 'math', 'percentage-calculator'],
  [80, 'math', 'percentage-increase-calculator'],
  [81, 'math', 'percentage-difference-calculator'],
  [82, 'math', 'fraction-calculator'],
  [83, 'math', 'ratio-calculator'],
  [84, 'math', 'proportion-calculator'],
  [85, 'math', 'average-calculator'],
  [86, 'math', 'weighted-average-calculator'],
  [87, 'math', 'scientific-calculator'],
  [88, 'math', 'exponent-calculator'],
  [89, 'math', 'square-root-calculator'],
  [90, 'math', 'cube-root-calculator'],
  [91, 'math', 'gcd-calculator'],
  [92, 'math', 'lcm-calculator'],
  [93, 'math', 'prime-number-checker'],
  [94, 'math', 'random-number-generator'],
  [95, 'math', 'factorial-calculator'],
  [96, 'math', 'permutation-calculator'],
  [97, 'math', 'combination-calculator'],
  [98, 'date-time', 'age-calculator'],
  [99, 'date-time', 'date-difference-calculator'],
  [100, 'date-time', 'days-between-dates'],
  [101, 'date-time', 'add-days-calculator'],
  [102, 'date-time', 'subtract-days-calculator'],
  [103, 'date-time', 'working-days-calculator'],
  [104, 'date-time', 'business-days-calculator'],
  [105, 'date-time', 'leap-year-checker'],
  [106, 'date-time', 'week-number-calculator'],
  [107, 'date-time', 'countdown-calculator'],
  [108, 'date-time', 'time-duration-calculator'],
  [109, 'date-time', 'time-zone-converter'],
  [110, 'date-time', 'unix-timestamp-converter'],
  [111, 'date-time', 'unix-timestamp-to-date'],
  [112, 'date-time', 'date-to-unix-timestamp'],
  [113, 'converters', 'length-converter'],
  [114, 'converters', 'weight-converter'],
  [115, 'converters', 'height-converter'],
  [116, 'converters', 'temperature-converter'],
  [117, 'converters', 'area-converter'],
  [118, 'converters', 'volume-converter'],
  [119, 'converters', 'speed-converter'],
  [120, 'converters', 'time-converter'],
  [121, 'converters', 'data-storage-converter'],
  [122, 'converters', 'energy-converter'],
  [123, 'converters', 'power-converter'],
  [124, 'converters', 'pressure-converter'],
  [125, 'converters', 'fuel-economy-converter'],
  [126, 'converters', 'frequency-converter'],
  [127, 'converters', 'angle-converter'],
  [128, 'health', 'bmi-calculator'],
  [129, 'health', 'bmr-calculator'],
  [130, 'health', 'tdee-calculator'],
  [131, 'health', 'calorie-calculator'],
  [132, 'health', 'ideal-weight-calculator'],
  [133, 'health', 'body-fat-calculator'],
  [134, 'health', 'water-intake-calculator'],
  [135, 'health', 'macro-calculator'],
  [136, 'health', 'protein-calculator'],
  [137, 'health', 'calorie-deficit-calculator'],
  [138, 'health', 'pregnancy-due-date-calculator'],
  [139, 'education', 'percentage-calculator'],
  [140, 'education', 'cgpa-calculator'],
  [141, 'education', 'gpa-calculator'],
  [142, 'education', 'marks-percentage-calculator'],
  [143, 'education', 'grade-calculator'],
  [144, 'education', 'attendance-calculator'],
  [145, 'education', 'required-attendance-calculator'],
  [146, 'education', 'study-time-calculator'],
  [147, 'education', 'exam-countdown'],
  [148, 'education', 'age-calculator'],
  [149, 'education', 'average-marks-calculator'],
  [150, 'developer', 'json-formatter'],
  [151, 'developer', 'json-validator'],
  [152, 'developer', 'json-minifier'],
  [153, 'developer', 'json-beautifier'],
  [154, 'developer', 'base64-encoder'],
  [155, 'developer', 'base64-decoder'],
  [156, 'developer', 'url-encoder'],
  [157, 'developer', 'url-decoder'],
  [158, 'developer', 'uuid-generator'],
  [159, 'developer', 'password-generator'],
  [160, 'developer', 'hash-generator'],
  [161, 'developer', 'jwt-decoder'],
  [162, 'developer', 'jwt-encoder'],
  [163, 'developer', 'regex-tester'],
  [164, 'developer', 'sql-formatter'],
  [165, 'developer', 'sql-minifier'],
  [166, 'developer', 'html-formatter'],
  [167, 'developer', 'css-formatter'],
  [168, 'developer', 'javascript-formatter'],
  [169, 'developer', 'typescript-formatter'],
  [170, 'developer', 'xml-formatter'],
  [171, 'developer', 'xml-validator'],
  [172, 'developer', 'yaml-formatter'],
  [173, 'developer', 'timestamp-converter'],
  [174, 'developer', 'cron-expression-generator'],
  [175, 'developer', 'color-converter'],
  [176, 'developer', 'lorem-ipsum-generator'],
  [177, 'developer', 'user-agent-parser'],
  [178, 'developer', 'ip-address-information-tool'],
  [179, 'developer', 'html-entity-encoder'],
  [180, 'developer', 'html-entity-decoder'],
  [181, 'text', 'word-counter'],
  [182, 'text', 'character-counter'],
  [183, 'text', 'sentence-counter'],
  [184, 'text', 'paragraph-counter'],
  [185, 'text', 'reading-time-calculator'],
  [186, 'text', 'case-converter'],
  [187, 'text', 'uppercase-converter'],
  [188, 'text', 'lowercase-converter'],
  [189, 'text', 'title-case-converter'],
  [190, 'text', 'remove-duplicate-lines'],
  [191, 'text', 'remove-extra-spaces'],
  [192, 'text', 'text-sorter'],
  [193, 'text', 'text-reverser'],
  [194, 'text', 'text-cleaner'],
  [195, 'text', 'slug-generator'],
  [196, 'text', 'lorem-ipsum-generator'],
  [197, 'text', 'find-and-replace'],
  [198, 'text', 'text-compare'],
  [199, 'text', 'line-counter'],
  [200, 'everyday', 'tip-calculator'],
  [201, 'everyday', 'split-bill-calculator'],
  [202, 'everyday', 'fuel-cost-calculator'],
  [203, 'everyday', 'fuel-mileage-calculator'],
  [204, 'everyday', 'electricity-cost-calculator'],
  [205, 'everyday', 'cooking-unit-converter'],
  [206, 'everyday', 'discount-calculator'],
  [207, 'everyday', 'age-calculator'],
  [208, 'everyday', 'random-picker'],
  [209, 'everyday', 'password-generator'],
  [210, 'everyday', 'date-calculator'],
  [211, 'everyday', 'sleep-calculator'],
  [212, 'everyday', 'wake-up-time-calculator'],
];

describe('specification catalogue', () => {
  it('lists all 212 numbered entries', () => {
    expect(CATALOGUE).toHaveLength(212);
    expect(CATALOGUE.map((c) => c[0])).toEqual(Array.from({ length: 212 }, (_, i) => i + 1));
  });

  it.each(CATALOGUE)('#%i is available in %s as /tools/%s', (_n, category, slug) => {
    const tool = TOOL_BY_SLUG.get(slug);
    expect(tool, slug).toBeDefined();
    expect(toolsInCategory(category).map((t) => t.slug)).toContain(slug);
  });

  it('has no registered tool outside the catalogue', () => {
    const catalogued = new Set(CATALOGUE.map((c) => c[2]));
    expect(ALL_TOOLS.filter((t) => !catalogued.has(t.slug)).map((t) => t.slug)).toEqual([]);
    expect(catalogued.size).toBe(ALL_TOOLS.length);
  });
});
